CPB100/lab3a/authorize_cloudshell.sh, CPB100/lab3b/authorize_dataproc.sh, CPB100/lab3b/sparkml/train_and_apply.py
Simplifies the process of authorizing access to Cloud SQL both from CloudShell and from Dataproc.
=> script out Lab 3a and 3b

courses/machine_learning/feateng/tftransform.ipynb
Hi, a little UX improvement ;)
-- Etsuji
=> Remove the hard-coded name of the model directory.

CPB100/lab4a/demandforecast.ipynb
Just came across this. 
Current code fails with unsupported operand type error. 
Converted  to  list and use numpy for the multiplication and the exponential.
Please let me know.
Thanks
Sergio
=> converting to list, use numpy for multiplication and exponentiation

blogs/predictions to ml engine/README.md, blogs/predictions to ml engine/Taxifare+Example+Machine+Learning+Engine.ipynb, blogs/predictions to ml engine/Taxifare+Example+Predictions+API.ipynb
I didn't have access to the repo so had to fork and PR from there. Please add me for write access if possible. Thanks!
=> Datalab Notebooks and README for Predictions API to ML Engine Migration Guide

courses/machine_learning/cloudmle/cloudmle.ipynb, courses/machine_learning/feateng/feateng.ipynb, courses/machine_learning/tensorflow/c_batched.ipynb, courses/machine_learning/tensorflow/d_experiment.ipynb
`google.cloud.ml` has changed to `google.datalab.ml`
=> updates for package name

blogs/endpointslambda/Apache2_0License.txt, blogs/endpointslambda/README.md, blogs/endpointslambda/aeflex-endpoints/app.yaml, blogs/endpointslambda/aeflex-endpoints/main.py, blogs/endpointslambda/aeflex-endpoints/openapi.yaml, blogs/endpointslambda/aeflex-endpoints/requirements.txt, blogs/endpointslambda/lambdafunctioninline.py
Please merge this code into the master.
=> sample code for Cloud Endpoints-AWS Lambda blog

.gitignore, courses/machine_learning/cloudmle/cloudmle.ipynb
Removed unnecessary imports that were causing errors for some students
Minor fix for a directory listing
Project/bucket/region initialization updated based on the experience with students
Removed outputs of all cells to allow students to see their own results and track their progress better
.gitingnore updated
=> Cloudmle notebook cleaned up

courses/machine_learning/datasets/create_datasets.ipynb
Currently the training set gets read twice
=> Fix reading csv file of the validation set

courses/dev-depl-windows/create-windows-vm/labinfra/qwiklabs.jinja, quests/vm-migration/labinfra/qwiklabs.jinja, quests/vm-migration/labinfra/qwiklabs_test_config.yaml, quests/windows/vm-migration/labinfra/qwiklabs.jinja, quests/windows/vm-migration/labinfra/qwiklabs_test_config.yaml
Hi Lak! Just trying to store my Deployment Manager templates in the right places in the repo. This is my first Git pull request ever, so don't hesitate to tell me where I have done the wrong thing.
=> My First Pull Request <3

courses/machine_learning/datasets/create_datasets.ipynb
Sorry, but "create issue" is disabled for this repo, so I just did the pull request. The modifications are very simple.
I participated of Bootcamp Google summit - SP and during the session qwickslabs I found this simple issues.
=> python 3 compatibility and ensuring np.arccos be between -1 and 1

quests/iotlab/cloudiot_mqtt_example_json.py, quests/iotlab/labinfra/qwiklabs.jinja
Include cloudiot_mqtt_example_json.py
Modify qwiklabs.jinja to rename VM from "iot" to "iot-device-simulator"
=> Add JSON version of script, change QL template to rename VM

courses/data_analysis/lab2/python/grep.py, courses/data_analysis/lab2/python/is_popular.py
Fixes problems with grep.py and is_popular.py by forcing module to wait
for pipeline to complete.
=> add wait_until_finish

CPB100/lab3b/sparkml/train_and_apply.py
Added flag to the read statements to prevent warnings.
=> Added flag to supress SSL warnings.

courses/unstructured/Unstructured-ML.ipynb
=> New unstructured data ML lab for DE class

CPB100/lab3a/authorize_cloudshell.sh, CPB100/lab3b/authorize_dataproc.sh
=> use CIDR as required by APIs

courses/machine_learning/cloudmle/cloudmle.ipynb, courses/machine_learning/cloudmle/taxifare/PKG-INFO, courses/machine_learning/feateng/feateng.ipynb, courses/machine_learning/feateng/taxifare/PKG-INFO, courses/machine_learning/tensorflow/c_batched.ipynb, courses/machine_learning/tensorflow/d_traineval.ipynb
In addition to changing the dataflow runner in the `feateng` notebook, I made a few other small changes.
Two of the notebooks in the `tensorflow` dir needed to have their default kernel changed to py2, otherwise there were syntax errors.
In the `cloudmle` notebook I needed to make a couple of patches-- LMK if you'd prefer to address them differently.  I had to copy the data files over from another directory, and as the `REPO` var is not defined in this notebook, I had to change how TensorBoard was invoked.
=> minor cleanup

courses/machine_learning/deepdive/05_artandscience/c_neuralnetwork.ipynb
Otherwise RMSE reported is wrong
=> lab5c: changed loss to average_loss

courses/machine_learning/cloudmle/cloudmle.ipynb, courses/machine_learning/feateng/feateng.ipynb, courses/machine_learning/feateng/hyperparam.ipynb, courses/machine_learning/tensorflow/a_tfstart.ipynb
Added warning about valid Cloud MLE regions to several notebooks.
Made tf.eager instructions more explicit.
=> Improved v12 lab instructions

courses/machine_learning/tensorflow/d_traineval.ipynb
Im taking the Data Engineering on google cloud platform course with George in Buenos Aires, and thought that this really tiny change could help others.
You can add it yourself to the code, i've seen this same hardcoded value in other files.
=> Stop TensorBoard

courses/streaming/publish/pubsub_pull.py
As per dmc's suggestion, I am adding this file in case you want to demo pull consumption during the labs
=> New file for pubsub demo

courses/machine_learning/deepdive/05_artandscience/d_customestimator.ipynb
Use PredictOutput over RegressionOutput/ClassificationOutput
=> Fixed export_outputs for SignatureDef MetaGraph

quests/scientific/coastline.ipynb
Hi, based on the feedback from the self-paced Labs tech writer team, I added a few guidance notes for those who are not familiar with Datalab and MLE.
=> Addind guidance notes

courses/developingapps/nodejs/cloudendpoints/start/prepare_environment.sh
Updated sudo npm install to npm install in prepare_environment.sh as the api2swagger wasn't being installed for user other than root.
=> Updated sudo npm install to npm install in prepare_environment.sh

courses/streaming/process/sandiego/create_cbt.sh
Command parameter has changed, causing script to fail in streaming data processing lab.
=> Replaced "--description" with "--display-name

courses/machine_learning/deepdive/05_artandscience/b_hyperparam.ipynb
Updating the tensorflow version to the version currently used by the datalab
=> Updating the tensorflow version

courses/machine_learning/deepdive/03_tensorflow/e_cloudmle.ipynb
=> Fix minor typo

courses/machine_learning/deepdive/03_tensorflow/c_dataset.ipynb
Remove the repetition of the import of tensorflow
=> Import of tensorflow twice

courses/developingapps/python/appengine/start/prepare_environment.sh, courses/developingapps/python/cloudstorage/start/prepare_environment.sh, courses/developingapps/python/firebase/start/prepare_environment.sh, courses/developingapps/python/firebase/start/quiz/webapp/static/client/index.html, courses/developingapps/python/kubernetesengine/start/prepare_environment.sh, courses/developingapps/python/pubsub-languageapi-spanner/start/prepare_web_environment.sh
Fixes to the prepare_environment.sh and index.html
=> Fixes to the prepare_environment.sh and index.html

.gitignore, courses/machine_learning/feateng/feateng.ipynb
this time with ssh key and email in agreement.
=> prevent stacktrace when no tensorboard instance running

courses/machine_learning/feateng/feateng.ipynb
Removed cell output by clearing all output before commit.
=> Fix up some magic cell commands.  Output cells have been cleared.

courses/machine_learning/deepdive/08_image/flowersmodel/model.py
d8c8b615bb12792543d18c0889eaf5a1fb63be07 fixed reshape issues when image was being augmented. We also need to do it when the image isn't being augmented.
=> Add NUM_CHANNELS to resize_billnear

courses/machine_learning/deepdive/08_image/labs/flowersmodel/model.py
d8c8b615bb12792543d18c0889eaf5a1fb63be07 fixed this for when augment=True.
=> Add NUM_CHANNELS to resize billinear

.gitignore, courses/machine_learning/deepdive/03_tensorflow/e_cloudmle.ipynb
in cloud_mle notebook.  Added a gitgnore mod to ignore the notebook comments and the json test file.
=> fixed up the magic cell commands and the tensorboard stop code 

courses/machine_learning/deepdive/09_sequence/sinemodel/model.py, courses/machine_learning/deepdive/09_sequence/sinewaves.ipynb
- added random seed for synthetic data generation so students will have more reproducible results
- added 'same as last' RMSE benchmark to compare against simple rules-based model
- changed CMLE to run on CPU since GPU didn't speed things up and was wasteful
- removed staging_bucket argument to CMLE job which was causing python modules to clutter root of the GCS bucket. now they will output as a sub directory of the output_dir
- added analysis of final results
=> updates to 09/sinewaves lab

blogs/tf_dataflow_serving/scripts/predict-batch-cmle.sh, blogs/tf_dataflow_serving/simulate_stream.py
A couple of changes in Github code snippets for cloud.google.com
=> fix code snippets for publishing

blogs/babyweight/babyweight.ipynb
Addressing some feedback on babyweight SPL, including removing some confusing messages (e.g. "hang on"), adding warnings about the warnings, and clarifying some of the code. Also adding the py2env code for installing Apache Beam.
=> Updating babyweight SPL

courses/data_analysis/deepdive/bigtable-exercises/python/ex3_solution.py, courses/data_analysis/deepdive/bigtable-exercises/python/main.py, courses/data_analysis/deepdive/composer-exercises/hello_world.py, courses/streaming/fromSHRP/to_messages.py, courses/streaming/publish/pubsub_pull.py, courses/unstructured/01-dataprocML.py, courses/unstructured/02-dataprocML.py, courses/unstructured/03-dataprocML.py, courses/unstructured/ML-Tests-Solution.ipynb, courses/unstructured/PySpark-Test-Solution.ipynb, courses/unstructured/Unstructured-ML.ipynb, courses/unstructured/lab2.py
Python 3 conversion. Nothing really big here. Mostly print statements and kernel updates to notebooks.
=> Conversion to Python 3 for DE track, C1, C2, C4

courses/machine_learning/cloudmle/cloudmle.ipynb, courses/machine_learning/cloudmle/taxifare/trainer/model.py, courses/machine_learning/datasets/create_datasets.ipynb, courses/machine_learning/tensorflow/a_tfstart.ipynb, courses/machine_learning/tensorflow/b_estimator.ipynb, courses/machine_learning/tensorflow/c_batched.ipynb, courses/machine_learning/tensorflow/d_traineval.ipynb
Updating print statements and kernels.
=> Updating courses/machine_learning/{cloudmle, tensorflow, datasets} to Python3

courses/machine_learning/deepdive/08_image/flowersmodel/model.py, courses/machine_learning/deepdive/08_image/labs/flowersmodel/model.py
Earlier commit added NUM_CHANNELS but resize_bilinear expects only a list with 2 elements.
=> Fix Invalid Function Arguments

courses/machine_learning/deepdive/09_sequence/labs/reusable-embeddings.ipynb
Creating C9 labs and cleaning up a bit
=> Removing comment typo

courses/machine_learning/deepdive/09_sequence/run-on-cloud-ml-engine.ipynb
The original TF without a PHD course uses this notebook and the current code still references it.
=> Adding run-on-cloud-ml-engine notebook

courses/machine_learning/feateng/feateng.ipynb
- Adding -y flag to conda update, which was causing issues
- Removing unnecessary apt-get; tested without and it worked fine
=> Apache Beam Issue

courses/machine_learning/deepdive/10_recommend/endtoend/endtoend.ipynb
=> Fixing the path

courses/machine_learning/feateng/feateng.ipynb
Clarifying instructions for feature engineering lab
=> Adding new instructions

courses/developingapps/python/devenv/server.py
=> Python3 Support: Fix ImportError and use bytes in outstream

courses/machine_learning/deepdive/10_recommend/labs/content_based_by_hand.ipynb
the arg of tf.tensordot is axes, not axis
=> fix typo in TODO guidance

blogs/rl-on-gcp/DQN_Breakout/rl_on_gcp/ReadMe.md, blogs/rl-on-gcp/ReadMe.md
Gif correct file path updated.
=> Added correct gif path to ReadMe

courses/machine_learning/deepdive/09_sequence/temperatures/utils/utils_batching.py
I'm Python newbie and I didn't understand the code because the comment was not consistent. I copied paste in a dirty Jupiter Notebook and I checked the shape values.
Now, it's more consistent and I understand what it's done by the code !!
(I didn't test all in the project and in this module, very small contribution ;) )
=> Fix comment for better understanding

courses/machine_learning/deepdive/02_generalization/repeatable_splitting.ipynb
There was a minor wording typo in the first cell. This fixes that sentence.
=> Update repeatable_splittying.ipynb with typo fix

courses/fast-and-lean-data-science/07_Keras_Flowers_TPU_solution.ipynb
Prompt to correct a problem in TPU lab related to a recent change. Not sure, though, if the change has other related factors as I just corrected this one concern. But the lab runs for me with this :-)
=> Add required prefetch() parameter.

courses/machine_learning/deepdive/08_image/flowers_fromscratch.ipynb, courses/machine_learning/deepdive/08_image/flowers_fromscratch_tpu.ipynb, courses/machine_learning/deepdive/08_image/labs/flowers_fromscratch.ipynb
Changed to python3 ('SyntaxError: invalid syntax' instead of jsonfied content otherwise)
=> One-liner changed to python3

courses/machine_learning/deepdive/01_bigquery/labs/a_sample_explore_clean.ipynb, courses/machine_learning/deepdive/01_bigquery/labs/b_bqml.ipynb
I've added the labs folder for 01_bigquery module and added some labs. Also, changed the PREDICT example in the b_bqml to be more relatable.
=> added 01_bigquery labs, changed PREDICT example in b_bqml solution

courses/machine_learning/deepdive/02_generalization/create_datasets.ipynb
closes #243 
Related to #290 
The bad import from #243 was never even used, so removing it should fix the problem.
=> Update create_datasets.ipynb, issue #243

courses/machine_learning/deepdive/02_tensorflow/e_traineval.ipynb, courses/machine_learning/deepdive/02_tensorflow/labs/e_traineval.ipynb
- Split existing `e_traineval.ipynb` into a sequence of solved exercises
- Created a version with the solution cells removed and placed it into the labs folder
=> e_traineval lab

courses/machine_learning/deepdive/09_sequence/labs/text_classification.ipynb
fix print, compatible with python3 syntax
=> fix print, compatible with python3 syntax

courses/machine_learning/deepdive/10_recommend/labs/wals.ipynb, courses/machine_learning/deepdive/10_recommend/labs/walsmodel/task.py, courses/machine_learning/deepdive/10_recommend/wals.ipynb, courses/machine_learning/deepdive/10_recommend/walsmodel/task.py
* "print" in *.ipynb file
* "import" in task.py
=> Fix py3 imcomatible codes in deepdive10

courses/data_analysis/lab2/python/JavaProjectsThatNeedHelp.py
Limited the max_num_workers on the pipeline to 5
=> Limited the max_num_workers on the pipeline to 5

courses/machine_learning/sme_academy/01_tf_estimator_deepdive.ipynb, courses/machine_learning/sme_academy/02_tfx_end_to_end.ipynb
* Added links to the tf.data.Dataset APIs documentations
=> Update TF Estimators DeepDive

courses/data_analysis/lab2/python/install_packages.sh, courses/machine_learning/deepdive/06_structured/serving/python_streaming.ipynb, courses/machine_learning/deepdive/08_image/flowers_fromscratch_tpu.ipynb, quests/dm_templates/init-script-001.sh, quests/tpu/flowers_resnet.ipynb
- Updated references to apache-beam python library
- Updated usage of pubsub python library
- Updated TF Version to 1.11 for TPU lab
- Added __init__.py for TPU lab
=> Ml dataflow pip bug

courses/machine_learning/deepdive/06_structured/4_preproc_tft.ipynb, courses/machine_learning/deepdive/10_recommend/wals_tft.ipynb, courses/machine_learning/feateng/tftransform.ipynb
Reverts GoogleCloudPlatform/training-data-analyst#422
=> Revert "Restricting num_workers to 2 for all TF Transform labs"

courses/machine_learning/deepdive/06_structured/4_preproc.ipynb, courses/machine_learning/deepdive/06_structured/labs/4_preproc.ipynb
- Updated cell to install the necessary dependencies for notebook.
- Limited the max_num_workers on the pipeline to 6.
=> Update: 4_preproc.ipynb

courses/machine_learning/deepdive/06_structured/labs/5_train.ipynb
=> Changing runtime instructions for lab version of babyweight CMLE lab

blogs/ncaa/dataflow/play_by_play.py, blogs/ncaa/dataflow/run_pipeline.sh
ingest NCAA mbb play-by-play data from cloud-training-demos gcs bucket into new BQ lab_dev dataset
run_pipeline.sh to kick off pipeline
=> dataflow pipeline and startup script

CPB100/lab4c/mlapis.ipynb
- Removed 'beta1' from the Speech API version.
=> Update: mlapis.ipynb notebook

courses/machine_learning/deepdive/10_recommend/hybrid_recommendations/hybrid_recommendations.ipynb, courses/machine_learning/deepdive/10_recommend/labs/hybrid_recommendations/hybrid_recommendations.ipynb
- Added the code for upgrading tensorflow.
=> Update: hybrid_recommendations notebook

courses/data-to-insights/demos/README.md, courses/data-to-insights/demos/authorized-view.sql, courses/data-to-insights/demos/bqml-classification-model.sql, courses/data-to-insights/demos/data-studio.md, courses/data-to-insights/demos/date-partitioned-tables.sql, courses/data-to-insights/demos/explore-data-with-sql.sql, courses/data-to-insights/demos/external-data-query.sql, courses/data-to-insights/demos/joining-weather-stations.sql, courses/data-to-insights/demos/scheduled-query.sql, courses/data-to-insights/demos/schemas-that-scale.sql, courses/data-to-insights/demos/vision-api.md, courses/data-to-insights/demos/wikipedia-10-billion.sql
source control and detailed instructions for each demo in v1.5 of data-to-insights
=> initial commit for data-to-insights demos

courses/machine_learning/deepdive/09_sequence/poetry.ipynb
- Added command to run tensorflow_hub.
- Added instruction to allow 'yes' in the command.
- Change the path to start tensorboard.
- Removed the 'Servo' from the model location.
- Modified the ml-engine version create command.
- Removed the cell which install alpha gcloud.
=> Update: poetry.ipynb notebook

courses/machine_learning/deepdive/01_bigquery/b_bqml.ipynb
Update: Corrected a typo in the IPython notebook.
=> Corrected a typo

README.md
**## Part 1**
Data Engineering course is structured as follows
1. Unstructured Data Analysis and then 2. Serverless Data Analysis. 
So modifying the order to keep in line with the coursera content. 
Cleaning up course & code to make it easy to read
=> readme update for Data Engineering Order

quests/dataflow/1_Basic_ETL/src/main/java/com/mypackage/pipeline/SamplePipeline.java
Mainly applying correct mapping to bq tables.
=> Fixed some bugs

courses/machine_learning/cloudmle/cloudmle.ipynb, courses/machine_learning/datasets/create_datasets.ipynb, courses/machine_learning/feateng/feateng.ipynb, courses/machine_learning/feateng/hyperparam.ipynb, courses/machine_learning/tensorflow/b_estimator.ipynb, courses/machine_learning/tensorflow/c_batched.ipynb, courses/machine_learning/tensorflow/d_traineval.ipynb
Replacing %bash with %%bash & %writefile with %%writefile for making notebook run in jupyterlab. 
Also removing unused datalab bigquery import.
=> making datalab notebook compatible with jupyterlab notebook

courses/machine_learning/deepdive/06_structured/4_preproc_tft.ipynb, courses/machine_learning/deepdive/10_recommend/hybrid_recommendations/hybrid_recommendations_preproc.ipynb
=> Update: hybrid_recommendations_preproc.ipynb and 4_preproc_tft.ipynb notebook

courses/data_analysis/deepdive/bigtable-exercises/src/main/java/com/google/cloud/bigtable/training/Ex0.java
Making semantic and a few logical modifications to better interoperate with the new codelab.
=> Modifying to better function with new Codelab

courses/data_analysis/deepdive/bigtable-exercises/src/main/java/com/google/cloud/bigtable/training/Ex1.java
Making semantic changes to better interoperate with the codelab.
=>  Modifying to better function with new Codelab

self-paced-labs/tensorflow-2.x/synthetic_features_and_outliers.ipynb, self-paced-labs/tensorflow-2.x/synthetic_features_and_outliers_solution.ipynb
-Added synthetic feature notebook along with the solution.
-Added necessary to do sections in the notebook.
=> Notebook for Tensorflow-2.x Self-Paced labs

courses/developingapps/nodejs/cloudstorage/end/server/public/client/app/quizzes/quiz-template.html, courses/developingapps/nodejs/cloudstorage/start/server/public/client/app/quizzes/quiz-template.html
This is PR 2/2 to fix a lab that referenced a relocated image file.
The corresponding lab instructions are PR 1/2.
The bug is http://b/138269057.
=> Enable .svg images to render with .png.

courses/machine_learning/deepdive/03_tensorflow/e_ai_platform.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/e_ai_platform.ipynb
- Added parenthesis in print function to run it on Python 3
=> Update: e_ai_platform.ipynb

courses/machine_learning/feateng/feateng.ipynb
per https://issuetracker.google.com/138810866
=> adding httplib param

courses/machine_learning/deepdive/08_image/labs/mnist_models.ipynb
- Updated the command from "gcloud ml-engine" to "gcloud ai-platform" to avoid warning.
- Updated the formatting of the table.
=> mnist_models.ipynb notebook

courses/machine_learning/deepdive/09_sequence/labs/sinewaves.ipynb, courses/machine_learning/deepdive/09_sequence/labs/sinewaves.ipynb_OLD, courses/machine_learning/deepdive/09_sequence/sinewaves.ipynb_OLD
renamed original ipynb to _OLD
=> fixes_to_multi_lab_ipynb

courses/machine_learning/intro_to_tensorflow/3_keras_sequential_api.ipynb
finished 3_keras_sequential_api notebook for review
=> creating 3_keras_sequential_api notebook for review

courses/machine_learning/deepdive/10_recommend/labs/content_based_using_neural_networks.ipynb
=> Second Update content_based_using_neural_networks.ipynb

courses/machine_learning/images/mnist_linear.ipynb
Creating new branch for tf2 development. Code approved per PR #551
=> Adding TF2 MNIST Linear Classifier Lab

quests/serverlessml/03_tfdata/labs/input_pipeline.ipynb, quests/serverlessml/03_tfdata/solution/input_pipeline.ipynb
=> Lab 3 TODOs and solution notebook

courses/machine_learning/deepdive2/how_google_does_mL/labs/placeholder.txt, courses/machine_learning/deepdive2/how_google_does_mL/solutions/placeholder.txt
=> naming_update

courses/machine_learning/images/mnist_models.ipynb, courses/machine_learning/images/mnist_trainer/trainer/__init__.py, courses/machine_learning/images/mnist_trainer/trainer/test.py
Thanks team!
Know there's a lot in here, so let me know if I can make reviewing this any easier.
Best,
Danielle
=> First Draft of MNIST DNN/CNN Labs

courses/machine_learning/recommendation_systems/als_bqml.ipynb
students can use models in cloud-training-demos while they wait for their to train
=> add pre-trained models as option to use

quests/rl/Dockerfile, quests/rl/README.md, quests/rl/hyperparam.yaml, quests/rl/setup.py, quests/rl/train_model.sh, quests/rl/trainer/model.py, quests/rl/trainer/model_test.py, quests/rl/trainer/trainer.py
Complete updating RL quest to TF2
=> Rlquest tf2docker

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/3_keras_sequential_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/3_keras_sequential_api.ipynb
- Made the minor syntax update.
=> Minor update: 3_keras_sequential_api.ipynb

courses/machine_learning/deepdive2/text_classification/solutions/custom_tf_hub_word_embedding.ipynb
I realized I forgot to add your comments from the previous PR before merging it. So I added them back in this PR with some correction in the intro from Elizabeth. 
Can you have a look that the text is now good?
=> incorporated Mike and Elizabeth corrections

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/1_core_tensorflow.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/2_dataset_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/3_keras_sequential_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/4_keras_functional_api.ipynb
removed code to make labs for keras sequential and functional api.
=> removed code to create labs

courses/machine_learning/deepdive/08_image/labs/flowers_fromscratch.ipynb
- Updated the code to use `gcloud ai-platform` instead of `gcloud ml-engine`.
- Removed "Monitoring training with TensorBoard" section.
=> "flowers_fromscratch.ipynb" notebook

courses/machine_learning/deepdive/09_sequence/text_classification.ipynb
- Removed "Monitor training with TensorBoard" section from the notebook.
- Updated TFVERSION to '1.14'
- Updated the commands as required.
- Updated 'ml-engine' with 'ai-platform' in the notebook.
=> OCBL071: Text Classification using TensorFlow/Keras on AI Platform

courses/machine_learning/deepdive/09_sequence/sinewaves.ipynb
- Removed "Monitor training with TensorBoard" section from the notebook.
- Updated TFVERSION to 1.14
=> Updated sinewaves.ipynb notebook

courses/machine_learning/feateng/feateng.ipynb
- Updated instructions in the notebook.
- Updated httplib2 version.
- Updated the commands to migrated the notebook in Python3.
=> OCBL040: Improve Machine Learning model with Feature Engineering 

courses/machine_learning/deepdive/05_artandscience/d_customestimator.ipynb, courses/machine_learning/deepdive/05_artandscience/labs/d_customestimator.ipynb
- Updated the correct 'simplernn' folder path.
- Added missing % in the code.
=> P2-P3 : OCBL045 Using Custom Estimators

courses/machine_learning/deepdive/10_recommend/composer_gcf_trigger/composertriggered.ipynb, courses/machine_learning/deepdive/10_recommend/labs/composer_gcf_trigger/composertriggered.ipynb
- Updated the notebook with Python3.
- Removed extra '}' from the code.
=> Composertriggered.ipynb notebook update

courses/machine_learning/deepdive/05_artandscience/labs/c_neuralnetwork.ipynb
- Updated the notebook with Python3.
=>  OCBL044: Using Neural Networks to build AI model 

courses/ai-for-finance/practice/aapl_regression_scikit_learn.ipynb
- Updated the practice notebook with Python3 kernel (aapl_regression_scikit_learn.ipynb).
=> OCBL089 - Building a Regression Model in AI Platform Notebooks

courses/machine_learning/deepdive2/recommendation_systems/solutions/als_bqml.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/als_bqml_hybrid.ipynb
Fixed a small bug where if students ran the data generation cell multiple times, they would get duplicate rows. See issue #602
=> Add learning objectives and fix bug for recommendation labs

courses/data_analysis/lab2/python/JavaProjectsThatNeedHelp_PY2_Version.py
update JavaProjectsThatNeedHelp to work with Python3
=> fix_py_sideinputs

courses/data_analysis/lab2/python/is_popular.py
- Updated the 'is_popular.py' file to remove the positional argument error
=> Python2 > 3: Serverless Data Analysis with Dataflow (Python) v1.3

courses/machine_learning/deepdive2/text_classification/labs/keras_for_text_classification.ipynb
the TODOs don't map 1-1 here but I think it's ok.
=> created lab from keras for text classification solution

courses/machine_learning/deepdive2/text_classification/labs/custom_tf_hub_word_embedding.ipynb
=> created lab from custom_tf_hub_word_embeddings solution

courses/machine_learning/deepdive/03_tensorflow/d_traineval.ipynb, courses/machine_learning/deepdive/03_tensorflow/e_ai_platform.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/d_traineval.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/e_ai_platform.ipynb, courses/machine_learning/deepdive/09_sequence/poetry.ipynb
- Adding tensorboard instructions in the notebook.
=> d_traineval.ipynb, e_ai_platform.ipynb, poetry.ipynb Notebook

courses/machine_learning/tensorflow/d_traineval.ipynb
- Added TensorBoard instructions.
=> "d_traineval.ipynb" Notebook 

CPB100/lab4a/demandforecast2.ipynb
- Updated the code to use "pandas_gbq".
- Removed 'authenticate_user' code.
=> "demandforecast2.ipynb" notebook 

courses/machine_learning/deepdive2/structured/labs/1a_explore_data_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/1a_explore_data_babyweight.ipynb
- Updated the pip commands to remove permission error.
- Reference Buganizer: http://b/147391649
=> ML on GCP: Exploring the Natality Dataset

courses/machine_learning/deepdive2/structured/labs/1b_prepare_data_babyweight.ipynb, courses/machine_learning/deepdive2/structured/labs/3a_bqml_baseline_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/1b_prepare_data_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/3a_bqml_baseline_babyweight.ipynb
- Updated 1b_prepare_data_babyweight.ipynb notebook with its solution notebook.
- Updated 3a_bqml_baseline_babyweight.ipynb notebook with its solution notebook.
- Updated pip commands with sudo.
- Updated the BUCKET value text.
=> deepdive2-notebook-updates

courses/machine_learning/deepdive2/structured/labs/4a_sample_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/4a_sample_babyweight.ipynb
- Updated the Google BigQuery library installation commands to eliminate the permission errors.
=> ML on GCP: Creating a Sampled Dataset

quests/serverlessml/01_explore/solution/explore_data.ipynb, quests/serverlessml/04_keras/labs/keras_dnn.ipynb, quests/serverlessml/04_keras/solution/keras_dnn.ipynb
Minor cleanup, plus bumped the CMLE prediction TF runtime version from 1.14  to 1.15 (which seems to be fine).
For Lab 1, updated the 'solution' BQ link to be consistent with the 'lab' link.
(I haven't gone through the rest of the labs yet, may submit another small PR after that).
=> minor fixes/updates to serverless ml materials

quests/serverlessml/06_feateng_keras/labs/taxifare_fc.ipynb, quests/serverlessml/06_feateng_keras/solution/taxifare_fc.ipynb, quests/serverlessml/07_caip/labs/train_caip.ipynb, quests/serverlessml/07_caip/solution/train_caip.ipynb
Lak, I made a couple of changes you might want to particularly check me on.  
You mention cost ($8.25) in a context of eval (not prediction) so I changed it to mention RMSE instead. I might have missed the intent.
Also, I changed the region in the container example (lab 07) b/c I think the buckets are created regionally (in prev lab) and I wanted to be consistent.
I changed the python version in the lab 07 notebooks since you had a non-py2-compatible print statement, and they seem to run fine on py3.
=> minor cleanup of serverlessml labs

quests/serverlessml/README.md
plus added instructions to create a qwiklabs account
=> remove event-specific info from the serverless ml README

courses/machine_learning/deepdive/06_structured/pipelines/README.md, courses/machine_learning/deepdive/06_structured/pipelines/containers/pipeline/mlp_babyweight.py
A few minor fixes for Pipeline Blog
=> Pipeline blog patch

blogs/explainable_ai/AI_Explanations_on_CAIP.ipynb
Fixed bug in notebook (feature naming) which led to unreasonable results for model predictions and feature attributions. Also did some minor clean-up of formatting.
=> Fixed bug with feature naming + Formatting changes

courses/machine_learning/deepdive/09_sequence/labs/text_classification.ipynb, courses/machine_learning/deepdive/09_sequence/text_classification.ipynb
- Updated the code cell as required.
- Updated the runtime version to 1.14.
- Reference buganizer: http://b/152397968
=> Text Classification using TensorFlow/Keras on AI Platform

courses/machine_learning/deepdive2/text_classification/labs/keras_for_text_classification.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/keras_for_text_classification.ipynb
- Added the “Create a Dataset from BigQuery” section in order to make notebook functionally independent in both target and solution notebook.
- Added the note section for the better understanding of user in both target and solution notebook.
- Removed the “Comparing the models” section from notebook in both target and solution notebook.
- Removed the empty cell in section from target notebook.
- Related Buganizer: http://b/150328756
=> Keras text classification fix

courses/machine_learning/deepdive/06_structured/5_train.ipynb, courses/machine_learning/deepdive/06_structured/labs/5_train.ipynb
- Added cell for deleting the .pyc files from Google Cloud folders.
=> 5_train.ipynb notebook updates

courses/machine_learning/deepdive2/image_classification/labs/tpu_models/trainer/model.py, courses/machine_learning/deepdive2/image_classification/labs/tpu_models/trainer/util.py
- Added missing "tpu_models" folder.
=> Transfer Learning on TPUs

courses/machine_learning/feateng/feateng.ipynb
- Updated the TFVERSION to 1.15 in “feateng.ipynb” notebook.
- Related Buganizer: http://b/152922799
=> ML on GCP: Improve ML model with Feature Engineering

courses/machine_learning/deepdive2/image_classification/labs/1_mnist_linear.ipynb, courses/machine_learning/deepdive2/image_classification/labs/3_tf_hub_transfer_learning.ipynb, courses/machine_learning/deepdive2/image_classification/solutions/1_mnist_linear.ipynb, courses/machine_learning/deepdive2/image_classification/solutions/3_tf_hub_transfer_learning.ipynb
- Removed the tensor-board part form “Evaluating Predictions” section of 1_mnist_linear.ipynb notebook.
- Updated the links in 1_mnist_linear.ipynb notebook.
- Updated the instruction in  1_mnist_linear.ipynb notebook.
- Updated the sequencing in 1_mnist_linear.ipynb notebook.
- Added the note for better understanding in 3_tf_hub_transfer_learning.ipynb notebook.
- Removed the empty cell from 3_tf_hub_transfer_learning.ipynb notebook.
- Related Buganizer: http://b/153365156
=> Image_Classification Notebooks Update

courses/machine_learning/deepdive2/text_classification/labs/reusable_embeddings.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/reusable_embeddings.ipynb
- Merged 'automl_for_text_classification' into 'reusable_embeddings' in labs folder
- Merged 'automl_for_text_classification' into 'reusable_embeddings' in solution folder
- Removed the “Comparing the models” section from the target notebook (under labs folder).
=> Making Independent: reusable_embeddings

courses/machine_learning/deepdive2/building_production_ml_systems/solutions/1_training_at_scale.ipynb, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/3_kubeflow_pipelines.ipynb, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/pipelines/Makefile, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/pipelines/components/trainjob/Dockerfile, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/pipelines/components/trainjob/main.sh, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/pipelines/create_pipeline.py, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/taxifare/Dockerfile, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/taxifare/scripts/env.sh, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/taxifare/scripts/submit.sh, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/taxifare/trainer/model.py, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/taxifare/trainer/task.py
- kfp lab uses now CAIP pipelines
- the taxifare trainer container no longer requires setup.py to build
- kfp lab can be used now directly within the CAIP jupyterlab
=> production ml: kubeflow pipeline lab

courses/machine_learning/deepdive2/building_production_ml_systems/labs/1_training_at_scale.ipynb, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/1_training_at_scale.ipynb
=> Syntax updated for variables in 1_training_at_scale.ipynb

courses/machine_learning/deepdive2/building_production_ml_systems/labs/0_export_data_from_bq_to_gcs.ipynb
- Copied 0_export_data_from_bq_to_gcs.ipynb
=> Add: 0_export_data_from_bq_to_gcs.ipynb

courses/machine_learning/deepdive2/building_production_ml_systems/labs/2_hyperparameter_tuning.ipynb, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/2_hyperparameter_tuning.ipynb
- Updated 2_hyperparameter_tuning for running 0_export_data_from_bq_to_gcs.ipynb
- Related buganizer: http://b/156016810
=> Update: 2 hyperparameter tuning.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/als_bqml_hybrid.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/als_bqml_hybrid.ipynb
- Adding section to import trained model into Hybrid
=> De-coupling dependency between ALS and Hybrid labs

courses/machine_learning/deepdive2/building_production_ml_systems/labs/1_training_at_scale.ipynb
Reverted the changes as taxifare folder is present
=> Fix-http://b/155347917

courses/machine_learning/deepdive2/launching_into_ml/labs/explore_data.ipynb
- Changed ownership from root to jupyter user
=> Update: labs/explore_data.ipynb

courses/machine_learning/deepdive2/launching_into_ml/labs/repeatable_splitting.ipynb
- Changed repo ownership to user.
=> Update: labs/repeatable_splitting.ipynb

courses/ai-for-time-series/README.md, courses/ai-for-time-series/notebooks/01-explore.ipynb, courses/ai-for-time-series/notebooks/02-model.ipynb, courses/ai-for-time-series/notebooks/03-cloud-training.ipynb
Adding course material which demonstrates how to use the Google Cloud AI Platform for time-series forecasting:
1. Time-series data visualization
2. Building models with TensorFlow and statsmodels packages
3. Training and predicting models in the Cloud using Training and Prediction Services
=> Adding time-series course material

courses/machine_learning/deepdive/03_tensorflow/c_dataset.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/c_dataset.ipynb
- Updated all the instructions in the c_dataset.ipynb notebook according to TensorFlow 2.X requirements.
- Added the command to check the version of Tensorflow installed in the target and solution notebook.
- Added the command to change the ownership of repo to user in the target and solution notebook.
- Related Buganizer: http://b/157450632
=> TF Migration 1.x >> TF 2.x (c_dataset.ipynb) Notebook Fix 

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/1_core_tensorflow.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/1_core_tensorflow.ipynb
- Added the command to change the ownership of repo to user in target solution notebook.
- Updated the command to check version of Tensorflow installed in target and solution notebook.
- Related Buganizer: http://b/157448982
=> TF Migration 1.x >> TF 2.x (1_core_tensorflow.ipynb) Notebook Fix

courses/machine_learning/deepdive/03_tensorflow/b_estimator.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/b_estimator.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/taxifare/trainer/model.py, courses/machine_learning/deepdive/03_tensorflow/taxifare/trainer/model.py
- Updated all the instructions in the b_estimator.ipynb notebook according to TensorFlow 2.X requirements.
- Updated all the dependencies in the model.py file according to tensorflow 2.X requirements in labs and solution folder.
- Added the command to check the version of Tensorflow installed in the target and solution notebook.
- Added the command to change the ownership of repo to user in the target and solution notebook.
- Reference Buganizer: http://b/157450101.
=> TF Migration 1.x >> TF 2.x (b_estimator.ipynb) Notebook Fix

courses/machine_learning/deepdive/03_tensorflow/d_traineval.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/d_traineval.ipynb
- Updated all the instructions in the d_traineval.ipynb notebook according to TensorFlow 2.X requirements.
- Added the command to check the version of Tensorflow installed in the target and solution notebook.
- Added the command to change the ownership of repo to user in the target and solution notebook.
- Related Buganizer: http://b/157448709
=> TF Migration 1.x >> TF 2.x (d_traineval.ipynb) Notebook Fix

courses/machine_learning/deepdive/04_features/a_features.ipynb, courses/machine_learning/deepdive/04_features/labs/a_features.ipynb
- Updated all the instructions in the notebook according to tensorflow 2.X requirements.
- Added the command to check version of Tensorflow installed in target and solution notebook.
- Related Buganizer: http://b/157449637
=> TF Migration 1.x >> TF 2.x (a_features.ipynb) Notebook Fix 

courses/developingapps/v1.2/java/devenv/pom.xml
Update pom versions to fix Java lab(s).
=> Fix broken Java lab.

courses/developingapps/v1.2/java/devenv/pom.xml
=> Fix odd extra chars.

courses/machine_learning/deepdive/06_structured/2_sample.ipynb, courses/machine_learning/deepdive/06_structured/labs/2_sample.ipynb
- Added the command to check version of Tensorflow installed in target and solution notebook.
- Related Buganizer: http://b/157724326
=> TF Migration 1.x >> TF 2.x (2_sample.ipynb) Notebook Fix

courses/developingapps/v1.2/java/datastore/start/pom.xml, courses/developingapps/v1.2/java/datastore/start/src/main/java/com/google/training/appdev/services/gcp/datastore/QuestionService.java
Update pom versions and remove small cosmetic problem.
=> Update pom versions.

courses/developingapps/v1.2/java/datastore/bonus/pom.xml, courses/developingapps/v1.2/java/datastore/end/pom.xml
=> Push fixes to end and bonus too.

courses/developingapps/v1.2/java/cloudstorage/end/pom.xml, courses/developingapps/v1.2/java/cloudstorage/start/pom.xml
Update pom so errors don't happen anymore.
=> Fix outdated pom.

courses/developingapps/v1.2/java/firebase/end/pom.xml, courses/developingapps/v1.2/java/firebase/start/pom.xml
=> Fix maven pom else app breaks.

courses/developingapps/v1.2/java/appengine/start/pom.xml
Need adjusted pom to deploy appengine app.
=> Fix appengine app to deploy.

courses/developingapps/v1.2/java/appengine/end/pom.xml, courses/developingapps/v1.2/java/appengine/start/pom.xml
Version needs to change, move to command line.
=> Move version to command line.

courses/machine_learning/deepdive/06_structured/5_train_bqml.ipynb
- Added the command to change the ownership of repo to user in notebook.
- Removed the instructions related to the tensorboard from notebook.
- Related Buganizer: http://b/157889602
=> TF Migration 1.x >> TF 2.x (5_train_bqml.ipynb) Notebook Fix

courses/machine_learning/deepdive/06_structured/4_preproc.ipynb, courses/machine_learning/deepdive/06_structured/labs/4_preproc.ipynb
- Added the command to check version of Tensorflow installed in target and solution notebook.
- Related Buganizer: http://b/157724331
=> TF Migration 1.x >> TF 2.x (4_preproc.ipynb) Notebook Fix

courses/machine_learning/deepdive/03_tensorflow/e_ai_platform.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/e_ai_platform.ipynb
- Removed all the instructions of the tensorboard.
- Removed all the instructions dependent on tensorboard.
- Related Buganizer: http://b/157449091
=> TF Migration 1.x >> TF 2.x (e_ai_platform.ipynb) Notebook Fix

courses/machine_learning/deepdive/06_structured/3_tensorflow_dnn.ipynb, courses/machine_learning/deepdive/06_structured/3_tensorflow_wd.ipynb, courses/machine_learning/deepdive/06_structured/labs/3_tensorflow.ipynb
- Added all the instructions according to the tensorflow version 2.X in target and solution notebook.
- Added the command to check version of Tensorflow installed in target and solution notebook.
- Related Buganizer: http://b/157724328
=> TF Migration 1.x >> TF 2.x (3_tensorflow.ipynb) Notebook Fix

courses/machine_learning/feateng/feateng.ipynb, courses/machine_learning/feateng/labs/feateng.ipynb, courses/machine_learning/feateng/labs/taxifare/trainer/model.py, courses/machine_learning/feateng/taxifare/trainer/model.py
- Updated all the dependencies in the model.py file according to tensorflow 2.X requirement.
- Updated all the instructions in the notebook according to tensorflow 2.X requirements.
- Added the command to change the ownership of repo to user in notebook.
- Related Buganizer: http://b/157624063
=> TF Migration 1.x >> TF 2.x (feateng.ipynb) Notebook Fix

courses/machine_learning/deepdive2/text_classification/labs/keras_for_text_classification.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/keras_for_text_classification.ipynb
- Updated the command to install TF 2.1 in the notebook.
- Reference buganizer: http://b/158191109
=> CBL192 - ML on GCP: Keras for Text Classification

courses/machine_learning/deepdive/10_recommend/content_based_by_hand.ipynb, courses/machine_learning/deepdive/10_recommend/labs/content_based_by_hand.ipynb
- Updated the tensorflow version 2.1
- Added command to ensure the right version of Tensorflow is installed
=> TF Migration 1.x >> TF 2.x: Notebook - Content based by hand.ipynb

courses/machine_learning/deepdive/09_sequence/labs/text_classification.ipynb, courses/machine_learning/deepdive/09_sequence/labs/txtclsmodel/trainer/model.py, courses/machine_learning/deepdive/09_sequence/labs/txtclsmodel/trainer/model_native.py, courses/machine_learning/deepdive/09_sequence/text_classification.ipynb, courses/machine_learning/deepdive/09_sequence/txtclsmodel/trainer/model.py, courses/machine_learning/deepdive/09_sequence/txtclsmodel/trainer/model_native.py
- Updated all the dependencies in the model.py file according to tensorflow 2.X requirement.
- Updated all the dependencies in the model_native.py file according to tensorflow 2.X requirement.
- Updated all the instructions in the notebook according to tensorflow 2.X requirements.
- Related Buganizer: http://b/158195653
=> TF Migration 1.x >> TF 2.x (text_classification.ipynb) Notebook Fix 

courses/machine_learning/tensorflow/c_batched.ipynb
- Updated the import tensorflow with compatibility to resolve the logging attribute error.
- Removed the instruction as required.
- Reference buganizer: http://b/158454563
=> Serverless ML - Lab 4 : Refactoring to add batching and feature-creation

courses/ahybrid/v1.0/AHYBRID045/scripts/create_gke.sh, courses/ahybrid/v1.0/AHYBRID045/scripts/create_remote.sh, courses/ahybrid/v1.0/AHYBRID045/scripts/env.sh, courses/ahybrid/v1.0/AHYBRID045/scripts/install.sh, courses/ahybrid/v1.0/AHYBRID045/scripts/services.sh, courses/ahybrid/v1.0/AHYBRID080/scripts/create_gke.sh, courses/ahybrid/v1.0/AHYBRID080/scripts/create_remote.sh, courses/ahybrid/v1.0/AHYBRID080/scripts/env.sh, courses/ahybrid/v1.0/AHYBRID080/scripts/install.sh, courses/ahybrid/v1.0/AHYBRID080/scripts/services.sh
New scripts for new labs setup.
=> Add scripts for AHYBRID labs.

quests/dei/WIT_Smile_Detector.ipynb
- Added command to ensure the right version of Tensorflow is installed
=> TF Migration 1.x >> TF 2.x: Notebook - Wit smile detector.ipynb

courses/machine_learning/tensorflow/d_traineval.ipynb
- Removed the instructions related to the tensorboard in notebook.
- Updated all the instructions in the notebook according to tensorflow 2.X requirements.
- Related Buganizer: http://b/158455516
=> TF Migration 1.x >> TF 2.x (d_traineval.ipynb) Notebook Fix 

courses/ahybrid/v1.0/AHYBRID080/config-management/gke-config-management.yaml, courses/ahybrid/v1.0/AHYBRID080/config-management/onprem-config-management.yaml, courses/ahybrid/v1.0/AHYBRID080/config/README.md, courses/ahybrid/v1.0/AHYBRID080/config/cluster/clusterrole-namespace-readers.yaml, courses/ahybrid/v1.0/AHYBRID080/config/cluster/clusterrolebinding-namespace-readers.yaml, courses/ahybrid/v1.0/AHYBRID080/config/namespaces/dev/namespace.yaml, courses/ahybrid/v1.0/AHYBRID080/config/namespaces/prod/namespace.yaml, courses/ahybrid/v1.0/AHYBRID080/config/namespaces/rolebinding-sre.yaml, courses/ahybrid/v1.0/AHYBRID080/config/namespaces/selector-sre-support.yaml, courses/ahybrid/v1.0/AHYBRID080/config/system/README.md, courses/ahybrid/v1.0/AHYBRID080/config/system/repo.yaml
Add configs for config management lab.
=> Add config management lab configs.

courses/machine_learning/deepdive/10_recommend/cf_softmax_model/solution/cfmodel_softmax_model_solution.ipynb, courses/machine_learning/deepdive/10_recommend/cf_softmax_model/target/cfmodel_softmax_model_target.ipynb
Replacing broken lab in Coursera course Adv ML on GCP.
=> Add CF and Softmax model lab for the Recommendation systems courses

courses/machine_learning/cloudmle/cloudmle.ipynb, courses/machine_learning/cloudmle/taxifare/trainer/model.py
- Updated the cells code to make it work with tensorflow 2.1.
=> TF Migration 1.x >> TF 2.x: Notebook - Cloudmle.ipynb 

courses/machine_learning/deepdive/09_sequence/labs/temperatures.ipynb, courses/machine_learning/deepdive/09_sequence/temperatures.ipynb
- Added the command to install TF version 1.15.3 in both target and solution notebook.
- Added the instruction cell as required.
- Reference buganizer: http://b/158201503
=> TF Migration 1.x >> TF 2.x (temperatures.ipynb) Notebook Fix

courses/machine_learning/tensorflow/a_tfstart.ipynb
- Updated all the dependencies according to tensorflow 2.X requirements.
- Related Buganizer: http://b/158454500
=> TF Migration 1.x >> TF 2.x (a_tfstart.ipynb) Notebook Fix

courses/machine_learning/deepdive/11_taxifeateng/tftransform.ipynb
- Added the command to install the required Tensorflow version in notebook.
- Related Buganizer: http://b/158738674
=> TF Migration 1.x >> TF 2.x (tftransform.ipynb) Notebook Fix

quests/serverlessml/01_explore/labs/explore_data.ipynb, quests/serverlessml/01_explore/solution/explore_data.ipynb, quests/serverlessml/04_keras/labs/keras_dnn.ipynb, quests/serverlessml/04_keras/solution/keras_dnn.ipynb, quests/serverlessml/06_feateng_keras/labs/taxifare_fc.ipynb, quests/serverlessml/06_feateng_keras/solution/taxifare_fc.ipynb
- Updated the runtime version with 2.1 in both target and solution notebook.
- Updated the notebook with chown and  tensorflow install command.
- Updated the python version of notebook with 3.7.6.
- Added chown command in explore_data.ipynb and keras_dnn.ipynb notebooks to work fine with DM.
- Reference buganizer: http://b/158738111
=> CBL075 - ML Workshop: Feature engineering with Keras in TensorFlow

quests/rl/early_rl/early_rl.ipynb
- Added the command to install the latest version of Tensorflow in notebook.
- Updated the instructions accordingly for better understanding.
- Related Buganizer: http://b/158890908
=> TF Migration 1.x >> TF 2.x (early_rl .ipynb) Notebook Fix 

courses/machine_learning/deepdive/10_recommend/content_based_preproc.ipynb, courses/machine_learning/deepdive/10_recommend/content_based_using_neural_networks.ipynb, courses/machine_learning/deepdive/10_recommend/labs/content_based_preproc.ipynb, courses/machine_learning/deepdive/10_recommend/labs/content_based_using_neural_networks.ipynb
- Updated the TF version 1.15.3 in 'content_based_using_neural_networks.ipynb' (target) notebook
- Removed the UTF-8 character encoding from 'content_based_preproc.ipynb' (Target & Solution) notebook
- Updated the TF version 2.1 in 'content_based_preproc.ipynb' notebook
- Reference buganizer: http://b/158293784
=> OCBL076 - Content-Based Filtering using Neural Networks

quests/rl/dqn/dqns_on_gcp.ipynb
- Updated the TF version 2.1 as required.
- Reference buganizer: http://b/158892684
=> OCBL124 - Reinforcement Learning DQN

blogs/batch_predictions/batch_predictions_keras.ipynb
https://medium.com/@dhodun/how-to-extend-a-keras-model-5effc083265c
=> Batch blog

courses/machine_learning/deepdive2/structured/labs/6_serving_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/6_serving_babyweight.ipynb
- Added an instruction in the notebook (solution & target) to train and deploy the Keras model on cloud AI platform.
- Reference buganizer: http://b/157727576
=> OCBL052 - Building an App Engine app to serve ML predictions

blogs/housing_prices/cloud-ml-housing-prices.ipynb
- Applied the changes made in the private repo
=> Copied file from vijaykyr repo

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/2_dataset_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/2_dataset_api.ipynb
- Added the command to install tensorflow version 2.1 in target and solution notebook.
- Related Buganizer: http://b/159694706
=> Tensorflow Upgradation for 2_dataset_api Notebook

courses/machine_learning/deepdive2/feature_engineering/labs/4_keras_adv_feat_eng-lab.ipynb
- Added the command to change the ownership of repo to user in target notebook.
- Related Buganizer: http://b/159888404
=> Update:Tensorflow Upgradation for 4_keras_adv_feat_eng Notebook

courses/machine_learning/deepdive2/launching_into_ml/labs/improve_data_quality.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/improve_data_quality.ipynb
- Added the command to install tensorflow version 2.1 in target and solution notebook.
- Related Buganizer: http://b/159978259
- Related PR: https://github.com/GoogleCloudPlatform/training-data-analyst/pull/1076
=> Tensorflow Upgradation for improve_data_quality Notebook

CPB100/lab4c/mlapis.ipynb
- Updated the installation command as per the requirement.
- Related Buganizer: http://b/158139918
=> Update: mlapis Notebook fix

courses/ahybrid/v1.0/AHYBRID050/scripts/create_gke.sh, courses/ahybrid/v1.0/AHYBRID050/scripts/env.sh, courses/ahybrid/v1.0/AHYBRID050/scripts/install.sh, courses/ahybrid/v1.0/AHYBRID050/scripts/services.sh
This branch contains new files for the courses/ahybrid/v1.0 directory. These files are used during the AHYBRID050 lab to do lab setup with GKE cluster and Anthos Service Mesh.
=> AHYBRID050-FEATURE-ADDASM

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/intro_logistic_regression_TF2.0.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/intro_logistic_regression_TF2.0.ipynb
- Added the lab TODOs in the target notebook as required.
- Updated the instructions in the solution notebook as required.
=> TODOs update: Notebook - intro_logistic_regression_TF2.0.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/load_images_tf.data.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/load_images_tf.data.ipynb
- Added the lab TODOs in the target notebook as needed.
- Updated the instructions in the target and solution notebook as needed.
=> TODOs update: Notebook - load_images_tf.data.ipynb

courses/machine_learning/deepdive2/image_classification/labs/1_mnist_linear.ipynb, courses/machine_learning/deepdive2/image_classification/solutions/1_mnist_linear.ipynb
=> Update: 1_mnist_linear Notebook

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/3_keras_sequential_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/3_keras_sequential_api.ipynb
- Updated the hyper-link for the notebook in labs and solution folder.
=> TODO's Task Addition for 3_keras_sequential_api Notebook

self-paced-labs/ai-platform-qwikstart/ai_platform_qwik_start.ipynb
=> Update: ai_platform_qwik_start.ipynb

courses/machine_learning/feateng/feateng.ipynb, courses/machine_learning/feateng/labs/feateng.ipynb
- Added the note section for better understanding of end user.
- Related Buganizer: http://b/161426232.
=> Update: feateng.ipynb Notebook

courses/machine_learning/deepdive2/launching_into_ml/labs/intro_linear_regression.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/intro_linear_regression.ipynb
- Updated the notebook (solution & target) instructions as required.
- Added the lab TODOs in the target notebook as needed.
=> OCBL184 - Introduction to Linear Regression

courses/machine_learning/deepdive2/launching_into_ml/labs/improve_data_quality.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/improve_data_quality.ipynb
- Updated the hypper-link for the notebook in labs and solution folder.
=> TODO's Task Addition for improve_data_quality notebook Notebook

courses/machine_learning/deepdive2/launching_into_ml/labs/decision_trees_and_random_Forests_in_Python.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/decision_trees_and_random_Forests_in_Python.ipynb
- Updated the hypper-link for the notebook in labs and solution folder.
=> TODO's Task Addition for decision_trees_and_random_forests_in_python Notebook

courses/machine_learning/deepdive2/feature_engineering/labs/2_bqml_adv_feat_eng-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/2_bqml_adv_feat_eng.ipynb
- Updated the Lab objectives in the target notebook according to the solution notebook.
- Updated the instructions in the target notebook according to the solution notebook.
- Updated the hyper-link for the notebook in labs and solution folder.
=> TODO's Task Addition for 2_bqml_adv_feat_eng.ipynb notebook 

courses/ai-for-finance/solution/momentum_backtest_losing_money.ipynb
- Removed the instructions related to the tensorboard.
- Related Buganizer: http://b/162194925
=> Momentum strategies Notebook Update 

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/basic_intro_logistic_regression.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/basic_intro_logistic_regression.ipynb
- Updated the title of the notebook in labs and solution folder.
- Updated the instructions of the notebook in labs and solution folder.
- Removed the unnecessary hyperlinks in labs and solution folder.
- Updated the content formatting in labs and solution folder.
- Added the hyper-link for the notebook in labs and solution folder.
- Related Buganizer: http://b/162121734
=> Basic Introduction to Logistic Regression Notebook Update

quests/dei/census/income_xgboost.ipynb
-Added the note section for better understanding.
-Related Buganizer: http://b/162264586
=> Update: income-xgboost Notebook

courses/machine_learning/deepdive2/feature_engineering/labs/1_bqml_basic_feat_eng_bqml-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/1_bqml_basic_feat_eng.ipynb
- Updated the lab TODOs in the target notebook as required
- Updated the instructions in solution & target notebook as required
=> OCBL151 - Performing basic feature engineering in BQML

quests/rl/early_rl/early_rl.ipynb
- Updated the command as required.
- Updated the typos as required.
- Added the note section for better understanding.
- Related Buganizer: http://b/162706288
=> Update: early_rl.ipynb Notebook

courses/machine_learning/deepdive2/building_production_ml_systems/labs/1_training_at_scale.ipynb, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/1_training_at_scale.ipynb
- Added the required code to export the required data.
- Corrected the minor typos as required.
- Updated the hyper-link for the notebook in labs and solution folder.
- Related Buganizer: http://b/162483308
=> Update: 1_Training_at_scale Notebook

blogs/housing_prices/cloud-ml-housing-prices.ipynb
Command is failing without flag.
=> Added runtime-version flag to versions create

courses/machine_learning/tensorflow/a_tfstart.ipynb
- Updated the hyperlink as required.
- Related Buganizer: http://b/164317916
=> Update: a_tfstart.ipynb Notebook

courses/machine_learning/deepdive2/image_classification/labs/2_mnist_models.ipynb, courses/machine_learning/deepdive2/image_classification/solutions/2_mnist_models.ipynb
- Related Buganizer: http://b/165173716, http://b/165170765
=> Update: 2_mnist_models.ipynb Notebook

courses/machine_learning/deepdive2/image_classification/labs/1_mnist_linear.ipynb, courses/machine_learning/deepdive2/image_classification/solutions/1_mnist_linear.ipynb
- Updated the `target` notebook instructions as required.
- Updated the `solution` notebook instructions as required.
- Updated the `typo` as required.
- Reference buganizer: `http://b/165167993`
=> Update: 1_mnist_linear.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/4_keras_adv_feat_eng-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/4_keras_adv_feat_eng.ipynb
- Added instruction to restart the kernel
- Added --user in the command to remove permission error 
- Related Buganizer: http://b/167999420
=> Notebook Update: CBL198

courses/ahybrid/v1.0/AHYBRID080/scripts/create_gke.sh, courses/ahybrid/v1.0/AHYBRID080/scripts/install.sh, courses/ahybrid/v1.0/AHYBRID080/scripts/tracing.yaml
- THIS IS A HOTFIX; LAB BASED ON THESE FILES IS CURRENTLY BROKEN
- Updated setup to do 1.6.8
- Added tracing yaml
=> AHYBRID080-UPDATE-TO-ASM

courses/ahybrid/v1.0/AHYBRID050/scripts/create_gke.sh, courses/ahybrid/v1.0/AHYBRID060/scripts/create_gke.sh, courses/ahybrid/v1.0/AHYBRID060/scripts/env.sh, courses/ahybrid/v1.0/AHYBRID060/scripts/install.sh, courses/ahybrid/v1.0/AHYBRID060/scripts/services.sh
- Updated install to ASM 1.6.8
=> 1.73/1.0.4 RELEASE: AHYBRID060 ASM/NEWLOGIC

courses/machine_learning/deepdive2/launching_into_ml/labs/improve_data_quality.ipynb, courses/machine_learning/deepdive2/launching_into_ml/labs/python.BQ_explore_data.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/improve_data_quality.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/python.BQ_explore_data.ipynb
- Added the required note in the “improve_data_quality.ipynb” and “python.BQ_explore_data.ipynb”.
=> Update: launching_into_ml notebook update

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/learning_rate.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/learning_rate.ipynb
- Updated the title of the notebook in labs and solution folder.
- Updated the instructions of the notebook in labs and solution folder.
- Removed the unnecessary hyperlinks in labs and solution folder.
- Updated the content formatting in labs and solution folder.
- Added the hyper-link for the notebook in labs and solution folder.
- Related Buganizer: http://b/168454765
=> Update: learning_rate Notebook

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/training_models_at_scale.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/training_models_at_scale.ipynb
- Added the output cells in both target and solution notebook.
- Updated the hyperlinks in both target and solution notebook.
- Added the note section for deprecation warning in both target and solution notebook.
- Removed the unnecessary instructions from both target and solution notebook.
- Added the command to install the required version of Bigquery in both target and solution notebook.
- Added the note section for restarting the kernel in both target and solution notebook.
=> Update: training_models_at_scale.ipynb Notebook

courses/machine_learning/deepdive2/launching_into_ml/labs/decision_trees_and_random_Forests_in_Python.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/decision_trees_and_random_Forests_in_Python.ipynb
- Added the cell output in the both target and solution notebook as required.
=> Notebook Update - decision_trees_and_random_Forests_in_Python.ipynb

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/export_data_from_bq_to_gcs.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/export_data_from_bq_to_gcs.ipynb
- Updated the `title` of the notebook in labs and solution folder.
- Added the `cell output` in the notebook for labs and solution folder.
- Added the command `%pip install google-cloud-bigquery==1.25.0` to resolve the error.
- Updated the instructions of the notebook in labs and solution folder.
- Updated the content formatting in labs and solution folder.
- Related Buganizer: http://b/168467504
=> OCBL202 - Notebook Update: export_data_from_bq_to_gcs.ipynb

blogs/babyweight/train_deploy.ipynb
- Added the output cells in the target notebook.
- Added the required instructions in the target notebook.
- Added the note section for deprecation warning in notebook.
- Removed the unnecessary instructions from target notebook.
- Added the command to install the required version of Bigquery in target notebook.
- Added the note section for restarting the kernel in target notebook.
=> Update: train_deploy.ipynb Notebook

courses/machine_learning/deepdive/11_taxifeateng/tftransform.ipynb
- Updated the typo as required.
- Updated the content formatting and instructions as required.
- Reference buganizer: http://b/168654674
=> Notebook Update: tftransform.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/write_low_level_code.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/write_low_level_code.ipynb
- Added the output cells in soution and target notebook.
- Corrected the typo's in soution and target notebook.
- Removed the unnecessary instructions.
- Updated the hyperlink as required.
=> Update: write_low_level_code.ipynb Notebook

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/2_dataset_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/2_dataset_api.ipynb
- Added the output cells in solution and target notebook.
- Corrected the typo's in solution and target notebook.
- Added the hyperlink in solution and target notebook.
- Removed the unnecessary instructions from solution and target notebook.
=> Update: 2_dataset_api.ipynb Notebook

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/3_keras_sequential_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/3_keras_sequential_api.ipynb
- Added the output cells in target notebook.
- Added the hyperlink in solution and target notebook.
- Removed the unnecessary instructions from solution and target notebook.
- Added the hyperlink in solution and target notebook.
=> Update: 3_keras_sequential_api.ipynb Notebook

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/basic_intro_logistic_regression.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/basic_intro_logistic_regression.ipynb
- Updated the title of the solution notebook.
- Added the output cells in solution and target notebook.
- Corrected the typo's in solution and target notebook.
- Removed the unnecessary instructions.
=> Update: basic_intro_logistic_regression.ipynb Notebook

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/hyperparameter_tuning.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/hyperparameter_tuning.ipynb, courses/machine_learning/deepdive2/building_production_ml_systems/labs/2_hyperparameter_tuning.ipynb, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/2_hyperparameter_tuning.ipynb
- Updated the notebook as per Gwendolyn's suggestion.
=> Update_notebook: Performing the Hyperparameter Tuning

courses/machine_learning/deepdive/09_sequence/labs/reusable-embeddings.ipynb, courses/machine_learning/deepdive/09_sequence/reusable-embeddings.ipynb
- Added the output cells in target notebook.
- Removed the unnecessary instructions from target notebook.
- Added the note section for deprecation warning in target notebook.
- Added the command to install the required version of Bigquery in target notebook.
- Added the note section for restarting the kernel target notebook.
- Related Buganizer: http://b/169392249
=> Update: reusable-embeddings.ipynb Notebook

courses/machine_learning/deepdive/09_sequence/labs/sinewaves.ipynb, courses/machine_learning/deepdive/09_sequence/sinewaves.ipynb
- Added the output cells in target notebook.
- Removed the unnecessary instructions from target notebook.
- Added the note section for deprecation warning in target notebook.
- Added the command to install the required version of BigQuery in target notebook.
- Added the note section for restarting the kernel target notebook.
- Related Buganizer: http://b/169392249
=> Update: sinewaves.ipynb Notebook

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/distributed_training.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/distributed_training.ipynb
- Added the required notebook in solution and target folder.
- Corrected the minor typos in both target and solution notebook.
- Removed the unnecessary instruction in both target and solution notebook.
- Added the learning objectives in both target and solution notebook.
- Added the hyperlinks in both target and solution notebook.
- Added the output cells in both target and solution notebook.
- Related Buganizer: http://b/169641119
=> Update: distributed_training.ipynb Notebook

courses/machine_learning/deepdive/09_sequence/labs/text_classification.ipynb, courses/machine_learning/deepdive/09_sequence/text_classification.ipynb
- Added the output cells in target notebook.
- Removed the unnecessary instructions from target notebook.
- Added the note section for deprecation warning in target notebook.
- Added the command to install the required version of BigQuery in target notebook.
- Added the note section for restarting the kernel target notebook.
- Related Buganizer: http://b/169392249
=> Update: text_classification.ipynb Notebook

courses/ai-for-finance/practice/aapl_regression_scikit_learn.ipynb, courses/ai-for-finance/solution/aapl_regression_scikit_learn.ipynb
- Added the output cells in both target and solution notebook.
- Removed the unnecesary instructions from both target and solution notebook..
- Added the note section for deprecation warning in both target and solution notebook..
- Added the command to install the required version of Bigquery in both target and solution notebook.
- Added the note section for restarting the kernel in both target and solution notebook.
- Added the command to change the ownership of repo to user in both target and solution notebook.
- Related Buganizer: http://b/167839713
=> Update: aapl_regression_scikit_learn.ipynb Notebook

courses/machine_learning/deepdive2/building_production_ml_systems/labs/4a_streaming_data_training.ipynb, courses/machine_learning/deepdive2/building_production_ml_systems/labs/4b_streaming_data_inference.ipynb, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/4a_streaming_data_training.ipynb, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/4b_streaming_data_inference.ipynb
- Added the instructions to perform the pre-requisite for the target notebook.
- Added the note section for deprecation warning in target notebook.
- Added the command to install the required version of Bigquery in target notebook.
- Added the note section for restarting the kernel target notebook.
- Added the command to change the ownership of repo to user in both target and solution notebook.
=> Update: 4b_streaming_data_inference.ipynb Notebook

courses/developingapps/v1.2/java/kubernetesengine/bonus/answer-backend-deployment.yaml, courses/developingapps/v1.2/java/kubernetesengine/bonus/backend-deployment.yaml, courses/developingapps/v1.2/java/kubernetesengine/bonus/frontend-deployment.yaml, courses/developingapps/v1.2/java/kubernetesengine/end/backend-deployment.yaml, courses/developingapps/v1.2/java/kubernetesengine/end/frontend-deployment.yaml, courses/developingapps/v1.2/java/kubernetesengine/start/backend-deployment.yaml, courses/developingapps/v1.2/java/kubernetesengine/start/frontend-deployment.yaml, courses/developingapps/v1.2/nodejs/containerengine/bonus/answer-backend-deployment.yaml, courses/developingapps/v1.2/nodejs/containerengine/bonus/backend-deployment.yaml, courses/developingapps/v1.2/nodejs/containerengine/bonus/frontend-deployment.yaml, courses/developingapps/v1.2/nodejs/containerengine/end/backend-deployment.yaml, courses/developingapps/v1.2/nodejs/containerengine/end/frontend-deployment.yaml, courses/developingapps/v1.2/nodejs/containerengine/start/backend-deployment.yaml, courses/developingapps/v1.2/nodejs/containerengine/start/frontend-deployment.yaml, courses/developingapps/v1.2/python/kubernetesengine/bonus/answer-backend-deployment.yaml, courses/developingapps/v1.2/python/kubernetesengine/bonus/backend-deployment.yaml, courses/developingapps/v1.2/python/kubernetesengine/bonus/frontend-deployment.yaml, courses/developingapps/v1.2/python/kubernetesengine/end/backend-deployment.yaml, courses/developingapps/v1.2/python/kubernetesengine/end/frontend-deployment.yaml, courses/developingapps/v1.2/python/kubernetesengine/start/backend-deployment.yaml, courses/developingapps/v1.2/python/kubernetesengine/start/frontend-deployment.yaml
=> Fix k8s deployment yamls to use apiVersion=apps/v1

courses/machine_learning/deepdive2/recommendation_systems/labs/als_bqml.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/als_bqml.ipynb
- Added the output of the cells as needed
- Removed the unnecessary instructions from the notebook (target & solution) as required
- Updated the BigQuery commands in the cells as required
- Reference buganizer: http://b/161415871
=> Update_notebook: als_bqml.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/als_bqml_hybrid.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/als_bqml_hybrid.ipynb
- Updated the output of the cells wherever necessary 
- Updated the instructions in the notebook as per end user's perpective
- Added the BigQuery commands in the cells as required.
- Updated the hyperlink for the reference notebook
- Reference buganizer: http://b/160069875
=> Update_notebook: als_bqml_hybrid.ipynb

courses/machine_learning/deepdive2/launching_into_ml/solutions/intro_linear_regression.ipynb
- Added the comments with required description in solution notebook
- Updated the formatting of the instructions in the notebook as needed.
=> Notebook_update: intro_linear_regression.ipynb

courses/data_analysis/deepdive/pubsub-exercises/exercise0-prework/java/labs/run.sh, courses/data_analysis/deepdive/pubsub-exercises/exercise0-prework/java/solution/run.sh, courses/data_analysis/deepdive/pubsub-exercises/exercise0-prework/python/labs/run.sh, courses/data_analysis/deepdive/pubsub-exercises/exercise0-prework/python/solution/run.sh
=> PubSub Academy

courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/learning_rate.ipynb
- Added the informative comments with all description in solution notebook.
- Adjusted the instructions for better understanding in solution notebook.
- Related Buganizer: http://b/171860757
=> Update: learning_rate.ipynb Notebook

courses/machine_learning/deepdive2/end_to_end_ml/labs/deploy_keras_ai_platform_babyweight.ipynb, courses/machine_learning/deepdive2/end_to_end_ml/labs/prepare_data_babyweight.ipynb, courses/machine_learning/deepdive2/end_to_end_ml/labs/train_keras_ai_platform_babyweight.ipynb, courses/machine_learning/deepdive2/end_to_end_ml/solutions/deploy_keras_ai_platform_babyweight.ipynb, courses/machine_learning/deepdive2/end_to_end_ml/solutions/prepare_data_babyweight.ipynb, courses/machine_learning/deepdive2/end_to_end_ml/solutions/train_keras_ai_platform_babyweight.ipynb
- Added the command in `prepare_data_babyweight.ipynb` to resolve the issue.
- Updated the hyperlink in `train_keras_ai_platform_babyweight.ipynb`.
- Corrected the typos in all the solution and target notebooks as required.
- Related Buganizer: http://b/172049372
=> Update: end_to_end_ml Notebooks

blogs/babyweight_keras/babyweight.ipynb
A minor update to the baby-weight (Keras version) notebook. Adding an example to make local predictions with the trained model.
=> A minor update to the baby-weight (Keras version) notebook.

quests/dei/WIT_Smile_Detector.ipynb
This allows the smile detection model to work in this lab.
=> downgrade h5py version and restart kernel

courses/developingapps/python/datastore/start/requirements.txt, courses/developingapps/python/pubsub-languageapi-spanner/start/requirements.txt
The set versions had reached eol and were causing dependency errors.
=> update dependency versions

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/3_keras_sequential_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/3_keras_sequential_api.ipynb
added region option to avoid error.
https://cloud.google.com/ai-platform/prediction/docs/release-notes#November_11_2020
=> fixed AI Platform Prediction error by adding region

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/write_low_level_code.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/write_low_level_code.ipynb
=> Notebook: write_low_level_code.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/2_dataset_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/2_dataset_api.ipynb
=> Notebook: 2_dataset_api.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/basic_intro_logistic_regression.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/basic_intro_logistic_regression.ipynb
=> ML DM Scripts: basic_intro_logistic_regression.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/4_keras_functional_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/4_keras_functional_api.ipynb
- Added the chown command in the target notebook.
- Added the instruction in the target and solution both.
=> ML DM Scripts Notebook Update: 4_keras_functional_api.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/1_bqml_basic_feat_eng_bqml-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/1_bqml_basic_feat_eng.ipynb
=> Notebook: 1_bqml_basic_feat_eng.ipynb

courses/machine_learning/deepdive2/launching_into_ml/labs/intro_logistic_regression.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/intro_logistic_regression.ipynb
=> ML DM Scripts: intro_logistic_regression.ipynb

blogs/form_parser/formparsing.ipynb
- Added the chown command to resolve the permission related issues in the notebook.
- Reference buganizer: http://b/179806747
=> Notebook_update: formparsing.ipynb

courses/business/managingmlprojects/labs/bias_tfdv_facets.ipynb, courses/business/managingmlprojects/solutions/bias_tfdv_facets.ipynb
- Updated the target and solution notebook as required
- Related buganizer: http://b/181001226
=> Update: OCBL198

courses/machine_learning/deepdive2/production_ml/labs/distributed_training.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/distributed_training.ipynb
- Copied notebook `distributed_training.ipynb` to the Production ML folder
- http://b/180991755
=> Relocate - notebook:  distributed_training.ipynb

courses/machine_learning/deepdive2/production_ml/labs/serving_ml_prediction.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/serving_ml_prediction.ipynb
- Created new notebook serving_ml_prediction.ipynb
- Updated the labs and solutions folder as required.
- Added the informative comments in the target and solution notebook.
- Reference buganizer: http://b/180991651
=> New Notebook: OCBL055 - Serving ML Predictions in batch and real-time

courses/machine_learning/deepdive2/production_ml/labs/keras.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/keras.ipynb
- Created the production_ml folder and added the notebook in labs and solutions folder.
- Updated the learning objectives and introduction in the both target and solution notebook.
- Removed the instructions as necessary.
- Updated the instructions as required.
- Updated the cell output in both labs and solutions notebook.
- Updated the informative comments in both target and solution notebook.
- Reference buganizer: http://b/180992027
=> Notebook Creation: Distributed Training with Keras - keras.ipynb

courses/machine_learning/deepdive2/text_classification/labs/classify_text_with_bert.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/classify_text_with_bert.ipynb
Adding a new lab and solution based on the tutorial to do sentiment analysis on IMDB dataset using small BERT
=> Adding a new lab for text classification using BERT 

courses/machine_learning/deepdive2/text_classification/labs/classify_text_with_bert.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/classify_text_with_bert.ipynb
Jupyter lab indexes files on AI platform constantly. Because of the size of the data file, it was causing the lab to crash.
=> Fixing data download bug which was causing classify_with_bert.ipynb lab to crash

courses/machine_learning/deepdive2/recommendation_systems/labs/basic_ranking.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/basic_ranking.ipynb
- Added a new notebook `basic_ranking.ipynb` in `recommendation_systems` folder.
=> Notebook_addition: recommendation_systems > basic ranking.ipynb

courses/machine_learning/deepdive2/production_ml/labs/keras.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/keras.ipynb
- Added the TODOs in the notebook:  keras.ipynb
- Reference buganizer: http://b/184340637
=> TODOs Update: Distributed Training with Keras

courses/machine_learning/deepdive2/production_ml/labs/serving_ml_prediction.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/serving_ml_prediction.ipynb
- Added the TODOs in the notebook:  serving_ml_prediction.ipynb
- Reference buganizer: http://b/184340113
=> TODOs Update: Serving ML Predictions in batch and real-time

courses/machine_learning/deepdive2/production_ml/labs/tfdv_advanced_taxi.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tfdv_advanced_taxi.ipynb
- Added the TODOs in the notebook:  `tfdv_advanced_taxi.ipynb`
- Updated the typos in the notebook.
- Reference buganizer: http://b/184340193
=> TODOs Update: TensorFlow Data Validation (Advanced)

courses/machine_learning/deepdive2/production_ml/labs/tpu_speed_data_pipelines.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tpu_speed_data_pipelines.ipynb
- Added the TODOs in the notebook:  tpu_speed_data_pipelines.ipynb
- Reference buganizer: http://b/184340559
=> TODOs Update: TPU-speed data pipelines: tf.data.Dataset and TFRecords

courses/machine_learning/deepdive2/recommendation_systems/labs/basic_ranking.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/basic_ranking.ipynb
- Added TODOs in the notebook.
- Updated the informative comments as required.
- Related buganizer: http://b/184718018
=> TODOs update: basic_ranking.ipynb 

courses/machine_learning/deepdive2/production_ml/labs/post_training_quant.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/post_training_quant.ipynb
- Added the learning objectives in the notebook as required.
- Added the comments as required in the notebook.
- Added the TODOs in the notebook as needed.
- Reference buganizer: http://b/185891162
=> Notebook_update: post_training_quant.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/multitask.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/multitask.ipynb
- Added the new notebook in the 'recommendation_systems' folder.
- Added the learning objectives in the notebook as required.
- Added the infomative comments in the notebook as required.
- Updated the necessary instructions in the notebook as required.
- Reference buganizer: http://b/186399514
=> New_notebook_addition: multitask.ipynb [Recommendation_systems]

courses/machine_learning/deepdive2/explainable_ai/labs/xai_image_caip.ipynb
- Add GCP XAI on CAIP lab for images.
- Tested with CAIP notebook instance with GPU attached.
- explainable-ai-sdk installed from head, tested with TF.2.3
=> Add XAI on CAIP image lab.

courses/machine_learning/deepdive2/explainable_ai/labs/xai_image_caip.ipynb
- Added explicit GPU device control for image lab.
- Remove remaining Colab instructions.
- Fixed CAIP model regions -> region argument.
=> XAI on CAIP lab minor fixes, style updates

courses/machine_learning/deepdive2/recommendation_systems/labs/featurization.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/featurization.ipynb
- Added the introduction and updated the instructions.
- Updated the typos and instructions as required.
- Reference buganizer: http://b/186398931
=> New notebook: Using side features: feature preprocessing - featurization.ipynb

courses/machine_learning/deepdive2/supplemental/labs/ai_explanations_image_gpu.ipynb
Lab is based on [pre-existing colab ](https://colab.sandbox.google.com/github/GoogleCloudPlatform/ai-platform-samples/blob/master/notebooks/samples/explanations/tf2/ai-explanations-image.ipynb#scrollTo=kV_NEAQwwH0e)
=> adding explainable ai lab to supplemental folder for future reference

courses/machine_learning/deepdive2/production_ml/labs/multi_worker_with_keras.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/multi_worker_with_keras.ipynb
- Updated the cell to resolved the attribute error: tf.distribute.experimental.MultiWorkerMirroredStrategy
- Updated the Introduction section as suggested.
- Added the cell to show TF version.
- Added the TODOs in the notebook: multi_worker_with_keras.ipynb
=> New Notebook: Production ML - multi_worker_with_keras.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/feat.cols_tf.data.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/feat.cols_tf.data.ipynb
- Updated the broken links: feature_columns and tf.data
- Reference buganizer: http://b/188021861
=> Notebook Update: feat.cols_tf.data.ipynb

self-paced-labs/tfx/tfx-ai-platform/install.sh, self-paced-labs/tfx/tfx-ai-platform/labs/lab_exercise.ipynb, self-paced-labs/tfx/tfx-ai-platform/solutions/lab_solution.ipynb
- Removing tuning as temporary workaround.
- Updated corresponding instructions and exercises.
=> GSP821 TFX lab updates - remove tuning, update instructions and exercises.

courses/machine_learning/deepdive2/launching_into_ml/labs/decision_trees_and_random_Forests_in_Python.ipynb
- Added the informative comments for TODOs in the target notebook for user convenience.
- Reference buganizer: http://b/189298971
=> Notebook Update: decision_trees_and_random_Forests_in_Python.ipynb

courses/machine_learning/deepdive2/production_ml/labs/parameter_server_training.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/parameter_server_training.ipynb
- Added the new notebook in the 'production_ml' folder.
- Updated the suggestions.
- Updated the TODOs.
- Buganizer: http://b/189919665
=> New notebook:  parameter_server_training.ipynb

quests/bq-teradata/01_teradata_bq_essentials/labs/bigquery_essentials_for_teradata_users.ipynb, quests/bq-teradata/01_teradata_bq_essentials/solution/bigquery_essentials_for_teradata_users.ipynb
- Updated the typos in the target and solution notebook.
- Updated the broken links as required.
- Reference buganizer: http://b/188698326
=> Notebook Update: bigquery_essentials_for_teradata_users.ipynb

quests/bq-optimize/01_baseline_performance/solution/explore_and_benchmark.ipynb, quests/bq-optimize/02_partition_and_clustering/solution/partition_and_cluster.ipynb
- Updated the cell code.
- Updated the broken links.
- Updated typos.
- Buganizer: http://b/188676620
=> Update: Clustering and Partitioning on a BigQuery Dataset (TPC-DS)

courses/machine_learning/deepdive2/launching_into_ml/labs/python.BQ_explore_data.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/python.BQ_explore_data.ipynb
- Updated the cell command with “distplot” by replacing “displot” in the solution notebook.
- Reference buganizer: http://b/190150334
=> Notebook Update: python.BQ_explore_data.ipynb

courses/machine_learning/deepdive2/production_ml/labs/distributed_training_with_TF.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/distributed_training_with_TF.ipynb
- Added the informative comments in the notebook
- Added the TODOs in the target notebook as required
- Updated the content formatting of the instructions in the notebook
- Reference buganizer: http://b/190707703
=> New_notebook_addition: distributed_training_with_TF

courses/machine_learning/deepdive2/launching_into_ml/labs/intro_linear_regression.ipynb
This is the student lab notebook, not the solution notebook.  (The link pointing to the solution notebook is correct.)
=> Fix incorrect self-description in lab notebook

courses/machine_learning/deepdive2/launching_into_ml/labs/explore_data.ipynb, courses/machine_learning/deepdive2/launching_into_ml/labs/python.BQ_explore_data.ipynb, courses/machine_learning/deepdive2/launching_into_ml/labs/repeatable_splitting.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/explore_data.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/python.BQ_explore_data.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/repeatable_splitting.ipynb
Fix the old Classic UI link that has been decommissioned as of October 1st.
Fix #1346
=> Fix notebook explore data links to BQ tables.

courses/developingapps/python/datastore/start/quiz/webapp/templates/home.html
The app is in the Python track while it currently says that it's Node.js
=> Update home.html - Change Node.js to Python

courses/machine_learning/deepdive2/production_ml/labs/parameter_server_training.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/parameter_server_training.ipynb
- Updated TF version to 2.5 in target and solution notebook.
- Commenting out few dependencies to resolve errors in the notebook.
=> Notebook_update: parameter_server_training.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/deep_recommenders.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/deep_recommenders.ipynb
- Updated the broken links in target and solution notebook.
=> Notebook_update: deep_recommenders.ipynb

self-paced-labs/vertex-pipelines/tfx/lab_exercise.ipynb, self-paced-labs/vertex-pipelines/tfx/pipeline/features.py, self-paced-labs/vertex-pipelines/tfx/pipeline/pipeline.py, self-paced-labs/vertex-pipelines/tfx/requirements.txt
- Add updated TFX 0.30.1 pipeline and lab files.
=> Initial Vertex Pipelines TFX SDK lab check-in

courses/machine_learning/deepdive2/feature_engineering/labs/3_keras_basic_feat_eng-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/3_keras_basic_feat_eng.ipynb
- Commented out the keras.utils dependency to resolve the error
- Removed the code cell which is fetching old TF version i.e. 2.1
=> Notebook_update: 3_keras_basic_feat_eng-lab.ipynb

courses/machine_learning/deepdive2/production_ml/labs/mlmd_tutorial.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/mlmd_tutorial.ipynb
- Updated the tfx version in the notebook as needed.
=> Notebook_update: mlmd_tutorial.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/tfrecord-tf.example.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/tfrecord-tf.example.ipynb
- Commented out the unnecessary command as the TF instance is already fetching TF 2.5 version as required.
=> Notebook_update: tfrecord-tf.example.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/1_bqml_basic_feat_eng_bqml-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/labs/4_keras_adv_feat_eng-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/1_bqml_basic_feat_eng.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/4_keras_adv_feat_eng.ipynb
- Commented out unnecessary commands which was fetching old TF version i.e. 2.1
- Updated the new commands in the notebook to install latest TF version i.e. 2.5
=> Notebooks_Update: 1_bqml_basic_feat_eng.ipynb & 4_keras_adv_feat_eng.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/2_bqml_adv_feat_eng-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/2_bqml_adv_feat_eng.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/feat.cols_tf.data.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/feat.cols_tf.data.ipynb
- Updated the following notebooks (target and solution) as necessary. Also, updated the cell outputs as required.
- feat.cols_tf.data.ipynb
- 2_bqml_adv_feat_eng.ipynb
=> Notebook Upgrade with TF 2.5

courses/machine_learning/deepdive2/production_ml/labs/training_example.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/training_example.ipynb
- Updated broken links.
- Updated the command to upgrade tensorflow version.
=> Notebook update: training_example.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/5_tftransform_taxifare.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/5_tftransform_taxifare.ipynb
- Updated the notebook cells as required with TF 2.5.
- Added a cell command to resolve the AttributeError.
=> Notebook-fix: 5_tftransform_taxifare.ipynb

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/hyperparameter_tuning.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/hyperparameter_tuning.ipynb
- Updated the notebook cells as required with TF 2.5.
=> Notebook-fix : hyperparameter_tuning.ipynb 

courses/machine_learning/deepdive2/launching_into_ml/labs/decision_trees_and_random_Forests_in_Python.ipynb, courses/machine_learning/deepdive2/launching_into_ml/labs/improve_data_quality.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/decision_trees_and_random_Forests_in_Python.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/improve_data_quality.ipynb
- Added the code cell to fetch latest TF version i.e. 2.5
- Removed the code which was fetching old TF version i.e 2.1
=> Notebooks_update: improve_data_quality.ipynb & decision_trees_and_random_Forests_in_Python.ipynb

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/learning_rate.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/labs/neural_network.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/learning_rate.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/neural_network.ipynb
- Commented out the dependencies for the notebook to work in TF 2.5 version
- Updated the outputs of the code cell to show TF 2.5 latest version
=> Notebooks_update: learning_rate.ipynb & neural_network.ipynb

courses/machine_learning/deepdive2/end_to_end_ml/labs/preproc.ipynb, courses/machine_learning/deepdive2/end_to_end_ml/solutions/preproc.ipynb
- Updated the dependencies in the notebook as per latest TF version 2.5
=> Notebook_update: preproc.ipynb

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/export_data_from_bq_to_gcs.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/export_data_from_bq_to_gcs.ipynb
- Added the code cell to fetch latest TF version in both target and solution notebook.
=> Notebook_update: export_data_from_bq_to_gcs.ipynb

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/training_models_at_scale.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/training_models_at_scale.ipynb
- Added the code cell to fetch latest TF version.
- Updated the TFversion.
- Updated the links.
=> Notebook_update: training_models_at_scale.ipynb

blogs/babyweight/train_deploy.ipynb
- Updated the TFversion to 2.3 in the notebook.
=> Notebook_update: train_deploy.ipynb

courses/machine_learning/deepdive2/production_ml/labs/serving_ml_prediction.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/serving_ml_prediction.ipynb
=> Notebook: serving_ml_prediction.ipynb

courses/machine_learning/deepdive2/text_classification/labs/rnn.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/rnn.ipynb
- Added the notebook in the labs and solution folder.
- Added the instructions in Introduction.
- Updated the broken link.
- Updated the TODOs.
=> Notebook: rnn.ipynb

courses/machine_learning/deepdive/10_recommend/content_based_by_hand.ipynb
- Updated the command to install the latest TF version 2.5
=> Notebook_update: content_based_by_hand.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/als_bqml.ipynb, courses/machine_learning/deepdive2/recommendation_systems/labs/als_bqml_hybrid.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/als_bqml.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/als_bqml_hybrid.ipynb
- Updated the `TFVERSION` to 2.5 as needed.
=> Notebook_update: als_bqml_hybrid.ipynb & als_bqml.ipynb

courses/machine_learning/tensorflow/a_tfstart.ipynb
- Updated the “a_tfstart.ipynb” notebook as necessary. Also, updated the cell outputs as required.
=> Notebook Upgrade with TF 2.5 - a_tfstart.ipynb

courses/machine_learning/tensorflow/b_estimator.ipynb
- Updated the latest TF version in the notebook as needed.
=> Notebook_update: b_estimator.ipynb

courses/machine_learning/deepdive/06_structured/5_train.ipynb
=> Notebook: 5_train.ipynb

courses/machine_learning/tensorflow/d_traineval.ipynb
- Updated the notebook to use lastest TF version
=> Notebook_update: d_traineval.ipynb

courses/machine_learning/deepdive/09_sequence/labs/text_classification.ipynb, courses/machine_learning/deepdive/09_sequence/text_classification.ipynb
- Updated the TF version in the notebook as needed.
=> Notebook_update: text_classification.ipynb

courses/machine_learning/deepdive2/image_classification/solutions/5_fashion_mnist_class.ipynb
=> Notebook: 5_fashion_mnist_class.ipynb

quests/rl/dqn/dqns_on_gcp.ipynb
- Updated the TF version to 2.5.
=> Notebook: dqns_on_gcp.ipynb

quests/rl/a2c/a2c_on_gcp.ipynb
- Updated the notebook with latest TF version.
=> Notebook_update: a2c_on_gcp.ipynb

quests/rl/early_rl/early_rl.ipynb
- Updated the latest TF version in the notebook as required.
=> Notebook_update: early_rl.ipynb

quests/dei/xgboost_caip_e2e.ipynb
- Added a note to ignore the error in `xgboost_caip_e2e.ipynb` notebook.
- Related buganizer: http://b/193725523
=> Update: GSP709

self-paced-labs/vertex-ai/vertex-ai-qwikstart/README.md, self-paced-labs/vertex-ai/vertex-ai-qwikstart/lab_exercise.ipynb, self-paced-labs/vertex-ai/vertex-ai-qwikstart/requirements.txt
- improved EDA plots and explanations.
- Fixes to requirements.txt to prevent unexpected pip dependency resolution.
- Add additional explanatory text.
- Remove cell output ahead of publishing.
=> Enhancements GSP917 Vertex AI Qwik Start.

self-paced-labs/vertex-ai/vertex-ai-qwikstart/lab_exercise.ipynb, self-paced-labs/vertex-ai/vertex-ai-qwikstart/requirements.txt
- Fix BQ EDA
- pin libraries, prevent higher TF version installing.
=> GSP917 Vertex AI: Qwikstart BQ EDA, dependency edits.

self-paced-labs/vertex-ai/vertex-ai-qwikstart/README.md, self-paced-labs/vertex-ai/vertex-ai-qwikstart/lab_exercise.ipynb
- Refactor to Vertex custom SA for direct custom training integration with Tensorboard for improved reliability.
- Add Vertex SA workflow to README setup instructions.
=> GSP917 Vertex AI: Qwik Start -> refactor Tensorboard section, add Vertex custom SA workflow

self-paced-labs/vertex-ai/vertex-ai-qwikstart/README.md, self-paced-labs/vertex-ai/vertex-ai-qwikstart/requirements.txt
- Upgrade library dependency.
- Remove unnecessary custom SA step from README.
=> GSP917 - Library upgrade, README updates.

self-paced-labs/vertex-ai/vertex-ai-qwikstart/lab_exercise.ipynb
Hotfix for b/193143812 ahead of ML Academy Webinar. Breaking change on deploying XAI through Vertex Endpoint for online explanations (predictions + feature attributions) without an identified workaround. Fix scheduled to be deployed 7/26.
=> Hotfix instructions for b/193143812 ahead of ML Academy Webinar.

courses/machine_learning/deepdive2/image_understanding/labs/transfer_learning_with_hub.ipynb, courses/machine_learning/deepdive2/image_understanding/solutions/transfer_learning_with_hub.ipynb
- Updated the cell output to show the latest TF version
=> Notebook_update: transfer_learning_with_hub.ipynb

courses/business/managingmlprojects/labs/bias_tfdv_facets.ipynb, courses/business/managingmlprojects/solutions/bias_tfdv_facets.ipynb
- Updated the cell output with TF 2.5 in target and solution notebook.
- Updated the notebook link in target and solution notebook.
=> Notebook_update: bias_tfdv_facets.ipynb

courses/machine_learning/deepdive2/image_classification/labs/1_mnist_linear.ipynb, courses/machine_learning/deepdive2/image_classification/solutions/1_mnist_linear.ipynb
- Updated the instructions in the notebook as needed.
=> Notebook_update: 1_mnist_linear.ipynb

courses/machine_learning/deepdive2/production_ml/labs/distributed_training.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/distributed_training.ipynb
- Updated the version in the notebook as needed.
=> Notebook_update: distributed_training.ipynb

courses/machine_learning/deepdive/03_tensorflow/e_ai_platform.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/e_ai_platform.ipynb
- Updated the TF version in the notebook. 
- Removed the unneccessary cell and description.
- Updated the target notebook as required.
=> Notebook_update: e_ai_platform.ipynb

courses/machine_learning/deepdive/03_tensorflow/c_dataset.ipynb, courses/machine_learning/deepdive/03_tensorflow/d_traineval.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/c_dataset.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/d_traineval.ipynb
- Updated the TF version in the notebook as needed.
=> Notebooks_update: c_dataset.ipynb & d_traineval.ipynb

courses/machine_learning/deepdive/05_artandscience/b_hyperparam.ipynb, courses/machine_learning/deepdive/05_artandscience/c_neuralnetwork.ipynb, courses/machine_learning/deepdive/05_artandscience/labs/b_hyperparam.ipynb, courses/machine_learning/deepdive/05_artandscience/labs/c_neuralnetwork.ipynb
- Updated the latest TF version in the notebook as required.
- Updated the necessary instructions in the notebook as needed.
=> Notebook_update: b_hyperparam.ipynb & c_neuralnetwork.ipynb

courses/machine_learning/deepdive2/image_understanding/labs/cnn.ipynb, courses/machine_learning/deepdive2/image_understanding/solutions/cnn.ipynb, courses/machine_learning/deepdive2/production_ml/labs/tfdv_advanced_taxi.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tfdv_advanced_taxi.ipynb
- Updated the changes as per the latest the TF version 2.5
=> Notebooks_update: tfdv_advanced_taxi.ipynb & cnn.ipynb

courses/machine_learning/deepdive2/production_ml/labs/tfdv_basic_spending.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tfdv_basic_spending.ipynb
- Updated required commands to install TensorFlow data validation, inorder to resolve `ModuleNotFoundError` error (In both target and solution notebook)
=> Update: tfdv_basic_spending.ipynb 

courses/machine_learning/deepdive2/text_classification/labs/word2vec.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/word2vec.ipynb
- Updated the TF version in the output cell.
- Updated the links.
=> Notebook_update: Word2vec.ipynb

courses/machine_learning/deepdive2/image_understanding/labs/transfer_learning.ipynb, courses/machine_learning/deepdive2/image_understanding/solutions/transfer_learning.ipynb
- Removed unnecessary command cell from both target and solution notebook.
- Updated the target and solution notebook links.
=> Notebook_update: transfer_learning.ipynb

courses/machine_learning/deepdive2/image_understanding/labs/Keras_Flowers_on_TPU.ipynb, courses/machine_learning/deepdive2/image_understanding/solutions/Keras_Flowers_on_TPU.ipynb
- Updated the TF version in target and solution notebook.
=> Notebook_update: Keras_Flowers_on_TPU.ipynb

courses/machine_learning/deepdive2/production_ml/labs/tpu_speed_data_pipelines.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tpu_speed_data_pipelines.ipynb
- Updated TensorFlow version output to 2.5.0 and updated required link (In both target and solution notebook)
=> Update: tpu_speed_data_pipelines.ipynb

courses/machine_learning/deepdive2/image_understanding/labs/segmentation.ipynb, courses/machine_learning/deepdive2/image_understanding/solutions/segmentation.ipynb, courses/machine_learning/deepdive2/production_ml/labs/training_example.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/training_example.ipynb, courses/machine_learning/deepdive2/recommendation_systems/labs/deep_recommenders.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/deep_recommenders.ipynb
- Updated the outputs to show the latest TF version.
=> Notebooks_update: segmentation.ipynb, training_example.ipynb and deep_recommenders.ipynb

courses/machine_learning/deepdive2/production_ml/labs/multi_worker_with_keras.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/multi_worker_with_keras.ipynb
- Updated TensorFlow version in the output section (In both target and solution notebook)
=> Update: multi_worker_with_keras.ipynb

courses/machine_learning/deepdive2/production_ml/labs/parameter_server_training.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/parameter_server_training.ipynb
- Updated TensorFlow version and required links (In both target and solution notebook)
=> Update: parameter_server_training.ipynb 

courses/machine_learning/deepdive2/production_ml/labs/distributed_training_with_TF.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/distributed_training_with_TF.ipynb
- Updated the cell output to show the latest TF version
=> Notebook_update: distributed_training_with_TF.ipynb

courses/machine_learning/deepdive2/text_classification/labs/word_embeddings.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/word_embeddings.ipynb
- Minor update in output of TF version (In both target and solution notebook)
=> Update: word_embeddings.ipynb 

courses/machine_learning/deepdive2/production_ml/labs/tpu_speed_data_pipelines.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tpu_speed_data_pipelines.ipynb
- Updated title as per the suggestion.
=> Title Update: tpu_speed_data_pipelines.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/load_diff_filedata.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/load_diff_filedata.ipynb
- Updated broken links in target and solution notebook.
- Buganizer: http://b/196342980
=> Notebook update: load_diff_filedata.ipynb

blogs/housing_prices/cloud-ml-housing-prices.ipynb
- Updated a broken link.
- Buganizer: http://b/194914485
=> Notebook update: cloud-ml-housing-prices.ipynb

self-paced-labs/vertex-ai/vertex-bqml/README.md, self-paced-labs/vertex-ai/vertex-bqml/lab_exercise.ipynb
Finish BQML XAI and conclusion sections.
=> GSP944 - finish Vertex BQML lab instructions.

courses/machine_learning/deepdive2/launching_into_ml/labs/automl_text_classification.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/automl_text_classification.ipynb
- Reference buganizer - http://b/197643206
=> OCBL280 - New Notebook: automl_text_classification.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/sdk-custom-image-classification-batch.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/sdk-custom-image-classification-batch.ipynb
- Related buganizer: http://b/197644824
=> New Notebook: sdk-custom-image-classification-batch.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/sdk-custom-image-classification-online.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/sdk-custom-image-classification-online.ipynb
- Added the learning objectives in the both `target` and `solution` notebook.
- Reference buganizer: http://b/197645192
=> New Notebook: sdk-custom-image-classification-online.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/6_gapic_feature_store.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/6_gapic_feature_store.ipynb
- Added the TODOs for the notebook.
- Updated typos as required.
- Reference buganizer: http://b/198145260
=> TODOs and Informative Comments Update: 6_gapic_feature_store.ipynb

courses/machine_learning/deepdive2/launching_into_ml/labs/automl_text_classification.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/automl_text_classification.ipynb
- Added the TODOs in the  target notebook and updated the solution file as necessary.
- Updated the typo as required.
- Reference buganizer: http://b/198583890
=> TODOs and Informative Comments Update: automl_text_classification.ipynb

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/gapic-vizier-multi-objective-optimization.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/gapic-vizier-multi-objective-optimization.ipynb
- Added the TODOs in the target notebook and updated the solution file as necessary.
- Related Buganizer: http://b/198584307
=> TODOs and Informative Comments Update: gapic-vizier-multi-objective-optimization.ipynb

courses/machine_learning/deepdive2/launching_into_ml/labs/automl-tabular-classification.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/automl-tabular-classification.ipynb
- Added the TODOs in the target notebook and updated the solution file as necessary.
- Related Buganizer: http://b/198146898
=> TODOs and Informative Comments Update: automl-tabular-classification.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/load_images_tf.data.ipynb
- Updated the output of the first cell of the solution notebook
- Reference Buganizer: http://b/199374886
=> Lab Updates: OCBL174

courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/feat.cols_tf.data.ipynb
- Updated the first cell of the solution notebook
- Reference Buganizer: http://b/199867569
=> Lab Updates: OCBL175

courses/machine_learning/deepdive2/production_ml/labs/keras.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/keras.ipynb
- Updated cell output as per TF 2.6 version
- Related Buganizer::  http://b/199827338
=> Update: keras.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/4_keras_functional_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/4_keras_functional_api.ipynb
- Updated the TF version to 2.3 in commands and cell outputs .
- Buganizer: http://b/199878734
=> Notebook_Update: 4_keras_functional_api.ipynb

courses/machine_learning/deepdive2/feature_engineering/solutions/2_bqml_adv_feat_eng.ipynb
- Updated the first cell of the solution notebook
- Reference Buganizer: http://b/199896445
=> Lab Updates: OCBL152

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/basic_intro_logistic_regression.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/basic_intro_logistic_regression.ipynb
- Updated the TF 2.6 version in cell output.
- Added the cell outputs.
- Reference buganizer: http://b/199877770
=> Notebook_update: basic_intro_logistic_regression.ipynb

courses/machine_learning/deepdive2/feature_engineering/solutions/2_bqml_adv_feat_eng.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/decision_trees_and_random_Forests_in_Python.ipynb
- Updated the solution notebook
- Reference Buganizer: http://b/199998821
=> Lab Updates: OCBL186

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/hyperparameter_tuning.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/hyperparameter_tuning.ipynb
- Updated the target and solution notebook as per TF 2.6 version
- Reference Buganizer: http://b/200036312
=> Lab Updates: OCBL201

courses/machine_learning/deepdive2/launching_into_ml/labs/bigquery.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/bigquery.ipynb
- Added the ToDo's in the target notebook and updated the solution file as required.
- Updated objectives as required
- Related Buganizer: http://b/198147165
=> TODO's and Informative Comments Update: bigquery.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/custom_layers_and_models.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/custom_layers_and_models.ipynb
- Added learning objectives and introduction in target and solution notebooks.
- Reference buganizer: http://b/199492720
=> New_Notebook: custom_layers_and_models.ipynb

courses/machine_learning/deepdive2/image_classification/solutions/5_fashion_mnist_class.ipynb
- Updated TF version in output cell
- Related Buganizer: http://b/200514758
=> Minor Update: 5_fashion_mnist_class.ipynb

courses/machine_learning/deepdive2/image_classification/labs/2_mnist_models.ipynb, courses/machine_learning/deepdive2/image_classification/solutions/2_mnist_models.ipynb
- Updated TF2.6 version and links in target and solution notebook
- Related buganizer: http://b/200513725
=> Update: 2_mnist_models.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/custom_layers_and_models.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/custom_layers_and_models.ipynb
- Added the TODOs in the target notebook and updated the solution file as necessary.
- Updated the formatting as required.
- Reference buganizer: http://b/200520093
=> TODOs and Informative Comments Update: custom_layers_and_models.ipynb

courses/machine_learning/deepdive2/production_ml/labs/serving_ml_prediction.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/serving_ml_prediction.ipynb
- Updated TF version in target and solution notebooks.
- Buganizer: http://b/200536662
=> Notebook_Update: serving_ml_prediction.ipynb

courses/machine_learning/feateng/feateng.ipynb
- Updated the TF version to `2.6`.
- Updated the Python version to `3.7`.
- Added a note to re-enable the `Dataflow API`.
- Related buganizer: http://b/200772550
=> Notebook Update: OCBL040 - feateng.ipynb

courses/machine_learning/deepdive/08_image/flowers_fromscratch.ipynb
- Updated the TF version in the notebook.
- Buganizer: http://b/200773044
=> Notebook_update: flowers_fromscratch.ipynb

courses/machine_learning/deepdive/03_tensorflow/b_estimator.ipynb, courses/machine_learning/deepdive/03_tensorflow/labs/b_estimator.ipynb
- Updated TF version to `2.6` in target and solution notebook.
- Buganizer: http://b/200792604
=> Notebook Update: OCBL102 - b_estimator.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/als_bqml.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/als_bqml.ipynb
- Updated TF version to 2.6 in target & solution notebook
- buganizer: http://b/200923840
=> Notebook_update - als_bqml.ipynb 

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/sdk-custom-image-classification-batch.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/sdk-custom-image-classification-batch.ipynb
- Updated command cells and instructions to use CPU Container image in both target and solution notebook
- Updated output cell as required
- Related Buganizer: http://b/197644824
=> Update: sdk-custom-image-classification-batch.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/intro_logistic_regression_TF2.0.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/intro_logistic_regression_TF2.0.ipynb
- Updated the first cell of the target and solution notebook
- Reference Buganizer: http://b/200805171
=> Lab Updates: OCBL178

courses/machine_learning/deepdive2/text_classification/labs/word_embeddings.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/word_embeddings.ipynb
- Updated TF version in solution and target notebook as required
- Related Buganizer: http://b/200931350
=> Minor update: word_embeddings.ipynb

courses/machine_learning/tensorflow/b_estimator.ipynb
- Updated TF2.6 version in the cell as required
- Related buganizer: http://b/200923204
=> Update: b_estimator.ipynb

courses/machine_learning/deepdive2/image_understanding/labs/segmentation.ipynb, courses/machine_learning/deepdive2/image_understanding/solutions/segmentation.ipynb
- Updated the TF version in cell output.
- Updated the cell outputs.
- Buganizer: http://b/200930788
=> Notebook_update: segmentation.ipynb

courses/machine_learning/deepdive/10_recommend/cf_softmax_model/solution/cfmodel_softmax_model_solution.ipynb, courses/machine_learning/deepdive/10_recommend/cf_softmax_model/target/cfmodel_softmax_model_target.ipynb
- Updated the TF version to 2.6 in notebook cell.
- Buganizer: http://b/200923762
=> Notbook_update: cfmodel_softmax_model_target.ipynb

courses/machine_learning/deepdive2/text_classification/labs/word2vec.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/word2vec.ipynb
- Updated the TF version in the output cell for target and solution notebook.
- Related buganizer: http://b/200931522
=> Notebook Update: OCBL232 - Word2vec.ipynb

courses/machine_learning/deepdive2/production_ml/labs/multi_worker_with_keras.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/multi_worker_with_keras.ipynb
- Updated the cell outputs.
- Buganizer: http://b/201048959
=> Notebook_update: multi_worker_with_keras.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/deep_recommenders.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/deep_recommenders.ipynb
- Added a command to use TF version 2.5.
- Added a note to restart the kernel.
- Buganizer: http://b/200931523
=> Notebook Update: OCBL257 - deep_recommenders.ipynb

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/sdk-custom-image-classification-batch.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/sdk-custom-image-classification-batch.ipynb
- Added the ToDo's in the target notebook and updated the solution notebook as required.
- Added the informative comments in both notebooks.
- Related Buganizer: http://b/201077401
=> TODOs and Informative Comments Update: sdk-custom-image-classification-batch.ipynb

courses/machine_learning/deepdive2/text_classification/labs/LSTM_IMDB_Sentiment_Example.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/LSTM_IMDB_Sentiment_Example.ipynb
- Updated the cell outputs in the notebook. 
- Updated the command in solution notebook.
- Buganizer: http://b/201255342
=> Notebook_update: LSTM_IMDB_Sentiment_Example.ipynb

courses/machine_learning/deepdive2/production_ml/labs/training_example.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/training_example.ipynb
- Updated TF version in both target and solution notebook
- Related Buganizer: http://b/201255451
=> Update: training_example.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/preprocessing_layers.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/preprocessing_layers.ipynb
- Updated cell output to show the latest TF version.
- Updated broken links.
- Buganizer: http://b/201255064
=> Notebook Update: OCBL283 - preprocessing_layers.ipynb

courses/machine_learning/deepdive2/production_ml/labs/parameter_server_training.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/parameter_server_training.ipynb
- Updated TF version to 2.6 as required in both target and solution notebook
- Related Buganizer: http://b/201144343
=> Notebook Update: parameter_server_training.ipynb

courses/machine_learning/deepdive2/image_understanding/labs/transfer_learning_with_hub.ipynb, courses/machine_learning/deepdive2/image_understanding/solutions/transfer_learning_with_hub.ipynb
- Updated cell output to show the latest TF version.
- Updated broken links.
- Buganizer: http://b/201049436
=> Notebook Update: OCBL220 - transfer_learning_with_hub.ipynb

courses/machine_learning/deepdive2/image_understanding/labs/cnn.ipynb, courses/machine_learning/deepdive2/image_understanding/solutions/cnn.ipynb
- Updated the cell outputs.
- Buganizer: http://b/201048519
=> Notebook_update: cnn.ipynb

courses/machine_learning/deepdive2/launching_into_ml/labs/intro_to_vertex_pipelines.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/intro_to_vertex_pipelines.ipynb
- Updated the instruction as necessary.
- Added the note as required.
- Updated the base_image version with tf2-cpu.2-6:latest
- Reference Buganizer: http://b/201378555
=> Notebook Update: intro_to_vertex_pipelines.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/basic_retrieval.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/basic_retrieval.ipynb
- Updated the commands in the notebooks.
- Updated the cell outputs.
- Buganizer: http://b/201256014
=> Notebook_update: basic_retrieval.ipynb

self-paced-labs/vertex-ai/vertex-distributed-tensorflow/Qwiklab_Running_Distributed_TensorFlow_using_Vertex_AI.ipynb
- Updated cell for bucket creation.
- Removed copyright information cell.
- Reference buganizer: http://b/201401477
=> Notebook Update: GSP971 - Qwiklab_Running_Distributed_TensorFlow_using_Vertex_AI.ipynb

self-paced-labs/vertex-ai/vertex-challenge-lab/README.md, self-paced-labs/vertex-ai/vertex-challenge-lab/requirements.txt, self-paced-labs/vertex-ai/vertex-challenge-lab/vertex-challenge-lab.ipynb
- Upgrade to TF 2.6
- Check-in files
=> Vertex skill badge challenge lab check-in

quests/vertex-ai/vertex-challenge-lab/vertex-challenge-lab.ipynb, self-paced-labs/vertex-ai/vertex-challenge-lab/vertex-challenge-lab-solution.ipynb
- Pin to prior component image 0.1.7 for model deployment workaround. b/203678136
=> Vertex challenge lab - model deployment workaround for b/203678136.

courses/ahybrid/v1.0/common/scripts/create_remote.sh
- downgrade remote cluster to 1.20.10; this fixes registration bug with gcloud and K8s 1.22
=> Hotfix for setup files used in labs AHYBIRD041/71/81

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/quickstart.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/quickstart.ipynb
- Added the notebook in labs and solutions folder.
- Updated the learning objectives and introduction in both target and solution notebook.
- Buganizer: http://b/204323986
=> New_Notebook: quickstart.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/time_series.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/time_series.ipynb
- Added the TODOs in the target and solution notebooks. 
- Buganizer: http://b/206075460
=> TODOs and Informative Comments Update: time_series.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/quickstart.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/quickstart.ipynb
- Added the TODOs in the target and solution notebooks.
- Enumerated the learning objectives.
- Buganizer: http://b/206076150
=> TODOs and Informative Comments Update: quickstart.ipynb

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/overfit_and_underfit.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/overfit_and_underfit.ipynb
- Added the learning objectives and introduction as required.
- Updated the notebook instructions as necessary.
- Reference buganizer: http://b/204417904
=> OCBL324 - Introduction to Overfit and Underfit

courses/ai-for-finance/practice/arima_model.ipynb, courses/ai-for-finance/solution/arima_model.ipynb
- Updated the commands in the cell.
- Updated the cell in practice notebook.
- Buganizer: http://b/203942938
=> Notebook_update: arima_model.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/imbalanced_data.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/imbalanced_data.ipynb
- Added TODOs in target and solution notebooks.
- Added informative comments in the notebooks.
- Buganizer: http://b/206076033
=> TODOs and Informative Comments Update: Imbalanced_data.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/train_models_with_tensorFlow_decision_forests.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/train_models_with_tensorFlow_decision_forests.ipynb
- Added the ToDo's in the target notebook and updated the solution notebook as required.
- Added the informative comments in both notebooks.
- Updated objectives as required
- Related Buganizer: http://b/207488383
=> TODOs and Informative Comments Update: train_models_with_tensorFlow_decision_forests.ipynb

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/overfit_and_underfit.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/overfit_and_underfit.ipynb
- Added the TODOs in the notebook: overfit_and_underfit.ipynb.ipynb
- Updated the target and solution notebook as necessary.
=> TODOs Update - OCBL324 - Introduction to Overfit and Underfit

courses/machine_learning/deepdive2/launching_into_ml/labs/automl-tabular-classification.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/automl-tabular-classification.ipynb
- Updated training duration 
- Related Buganizer: http://b/208392721
=> Notebook Update: OCBL282 

self-paced-labs/vertex-ai/vertex-challenge-lab/bert-sentiment-classifier/Dockerfile, self-paced-labs/vertex-ai/vertex-challenge-lab/bert-sentiment-classifier/requirements.txt, self-paced-labs/vertex-ai/vertex-challenge-lab/bert-sentiment-classifier/trainer/model.py, self-paced-labs/vertex-ai/vertex-challenge-lab/bert-sentiment-classifier/trainer/task.py, self-paced-labs/vertex-ai/vertex-challenge-lab/requirements.txt, self-paced-labs/vertex-ai/vertex-challenge-lab/vertex-challenge-lab-solution.ipynb
- Update lab dependencies and remove workaround to address breakage.
```
google-cloud-aiplatform==1.8.0
tensorflow-text==2.6.0
tf-models-official==2.6.0
kfp==1.8.9
google_cloud_pipeline_components==0.2.0
```
- Re-write pipeline for new API.
- Add clarifying lab instruction text.
=> Dependency conflict fixes for Vertex skill badge challenge lab solution.

quests/vertex-ai/vertex-challenge-lab/requirements.txt, quests/vertex-ai/vertex-challenge-lab/vertex-challenge-lab.ipynb
Update lab dependencies and remove workaround to address breakage.
```
google-cloud-aiplatform==1.8.0
tensorflow-text==2.6.0
tf-models-official==2.6.0
kfp==1.8.9
google_cloud_pipeline_components==0.2.0
```
- Re-write pipeline for new API.
- Add clarifying lab instruction text.
=> Update Vertex challenge lab for SPL catalog.

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/preprocessing_layers.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/preprocessing_layers.ipynb
- Updated the toy dataset in target and solution notebook.
- Updated the cell outputs as per toy dataset. 
- Updated the instruction.
- Updated the execution counts.
- Buganizer: http://b/211959565
=> Notebook_update: preprocessing_layers.ipynb

courses/machine_learning/deepdive2/production_ml/labs/tfdv_advanced_taxi.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tfdv_advanced_taxi.ipynb
- Updated the output text and link in target and solution notebook
- Related buganizer: http://b/215658798
=> Update: tfdv_advanced_taxi.ipynb

courses/machine_learning/deepdive2/text_classification/labs/keras_for_text_classification.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/keras_for_text_classification.ipynb
- Updated the instructions in solution notebook.
- Updated the hyperlinks.
- Buganizer: http://b/217263859
=> Notebook_update - keras_for_text_classification.ipynb

courses/machine_learning/deepdive2/structured/labs/4a_sample_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/4a_sample_babyweight.ipynb
- Updated the commands in the notebook cells.
- Buganizer: http://b/217242789
=> Notebook_update: 4a_sample_babyweight.ipynb

quests/serverlessml/02_bqml/labs/first_model.ipynb, quests/serverlessml/02_bqml/solution/first_model.ipynb
- Updated the commands in target and solution notebooks.
- Buganizer: http://b/217203374
=> Notebook_update: first_model.ipynb

courses/machine_learning/deepdive2/structured/labs/3a_bqml_baseline_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/3a_bqml_baseline_babyweight.ipynb
- Updated commands in `3a_bqml_baseline_babyweight.ipynb` file in labs and solutions folder
- Reference buganizer: http://b/217241445
=> CBL159 - ML on GCP: BigQuery ML Model Baseline

courses/machine_learning/deepdive2/time_series_prediction/labs/optional_1_data_exploration.ipynb, courses/machine_learning/deepdive2/time_series_prediction/solutions/optional_1_data_exploration.ipynb
=> Update: CBL168 Data Exploration

courses/machine_learning/deepdive2/building_production_ml_systems/labs/3_kubeflow_pipelines.ipynb, courses/machine_learning/deepdive2/building_production_ml_systems/solutions/3_kubeflow_pipelines.ipynb
- Updated the instructions in target and solution notebook as required
- Related buganizer: http://b/217272424
=> Notebook update: 3_kubeflow_pipelines.ipynb

courses/machine_learning/deepdive2/image_classification/labs/4_tpu_training.ipynb, courses/machine_learning/deepdive2/image_classification/solutions/4_tpu_training.ipynb
- Updated the hyperlink in target and solution notebooks.
- Added the instruction to access target and solution notebooks.
- Buganizer: http://b/217267534
=> Notebook_update: 4_tpu_training.ipynb

courses/machine_learning/deepdive2/structured/labs/1a_explore_data_babyweight.ipynb
- Buganizer: http://b/217241443
=> Notebook_update: 1a_explore_data_babyweight.ipynb

courses/machine_learning/deepdive2/time_series_prediction/labs/3_modeling_bqml.ipynb, courses/machine_learning/deepdive2/time_series_prediction/solutions/3_modeling_bqml.ipynb
- Updated the instructions in target and solution notebook
- Buganizer: http://b/217244201
=> Notebook Updates - 3_modeling_bqml.ipynb

courses/machine_learning/deepdive2/structured/labs/3b_bqml_linear_transform_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/3b_bqml_linear_transform_babyweight.ipynb
- Updated commands in `3b_bqml_linear_transform_babyweight.ipynb` file in labs and solutions folder
- Reference buganizer: http://b/217242293
=> CBL160 - ML on GCP: BigQuery ML Model Linear Feature Engineering/Transform

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/hyperparameter_tuning.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/hyperparameter_tuning.ipynb
- Updated the typos and instructions in target and solution notebook as required
- Related buganizer: http://b/217273162
=> Notebook update: hyperparameter_tuning.ipynb

courses/machine_learning/deepdive2/structured/labs/2_automl_tables_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/2_automl_tables_babyweight.ipynb
- Updated the notebook path in target and solution notebook
- Buganizer: http://b/217240854
=> Notebook_Update: 2_automl_tables_babyweight.ipynb

courses/machine_learning/deepdive2/structured/solutions/1b_prepare_data_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/4c_keras_wide_and_deep_babyweight.ipynb
- Updated instructions to add bucket ID
- Reference Buganizer: http://b/217243388
=> CBL165 Notebook Updates

courses/machine_learning/deepdive2/image_classification/labs/2_mnist_models.ipynb, courses/machine_learning/deepdive2/image_classification/solutions/2_mnist_models.ipynb
- Added the cell to set ai_platform region in both target and solution notebook.
=> Notebook Update: 2_mnist_models.ipynb

courses/machine_learning/deepdive2/structured/labs/3c_bqml_dnn_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/3c_bqml_dnn_babyweight.ipynb
- Updated the instructions.
- Updated the commands.
- Buganizer: http://b/217242788
=> Notebook_update: 3c_bqml_dnn_babyweight.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/7_get_started_with_feature_store.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/7_get_started_with_feature_store.ipynb
- Reference buganizer: http://b/215697692
=> New Notebook: 7_get_started_with_feature_store.ipynb

courses/machine_learning/deepdive/10_recommend/labs/wals.ipynb
- Updated the instructions as required
- Updated the hyperlink
- Updated the Tf version from 1.13 to 1.15
- Buganizer: http://b/220348094
=> Notebook_Update: wals.ipynb

courses/machine_learning/deepdive2/launching_into_ml/labs/automl-tabular-classification.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/automl-tabular-classification.ipynb
- Added a note in target and solution notebooks.
=> Notebook_update: automl-tabular-classification.ipynb

quests/serverlessml/04_keras/labs/keras_dnn.ipynb, quests/serverlessml/04_keras/solution/keras_dnn.ipynb, quests/serverlessml/06_feateng_keras/labs/taxifare_fc.ipynb, quests/serverlessml/06_feateng_keras/solution/taxifare_fc.ipynb
- Update keras_dnn.ipynb
- Update taxifare_fc.ipynb
- Buganizer: http://b/220357700
=> CBL078 - Notebook_updates

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/sdk_custom_tabular_regression_online_explain.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/sdk_custom_tabular_regression_online_explain.ipynb
- Reference buganizer: http://b/222226977
=> New Notebook: OCBL348 - Vertex SDK: Custom Training Tabular Regression Models for Online Prediction and Explainability

courses/machine_learning/deepdive2/production_ml/labs/tfdv_advanced_taxi.ipynb, courses/machine_learning/deepdive2/production_ml/labs/tfdv_basic_spending.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tfdv_advanced_taxi.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tfdv_basic_spending.ipynb
- Updated pyarrow version to 5.0.0
- Updated a note in target and solution notebook.
=> Notebook Update: "tfdv_basic_spending.ipynb" and "tfdv_advanced_taxi.ipynb"

courses/machine_learning/deepdive2/text_classification/labs/custom_tf_hub_word_embedding.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/custom_tf_hub_word_embedding.ipynb
- Updated the instruction.
- Updated the hyperlink.
- Buganizer: http://b/222631923
=> Notebook_update: custom_tf_hub_word_embedding.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/5_tftransform_taxifare.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/5_tftransform_taxifare.ipynb
- Updated the lab name in the notebook.
- Updated the target and solution notebook path.
- Buganizer: http://b/223983752
=> Notebook_update: 5_tftransform_taxifare.ipynb

courses/machine_learning/deepdive2/how_google_does_ml/labs/automl-tabular-classification.ipynb, courses/machine_learning/deepdive2/how_google_does_ml/solutions/automl-tabular-classification.ipynb
- Updated notebook path for target and solution notebook to `how_google_does_ml` course.
=> Notebook path update: automl-tabular-classification.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/content_based_by_hand.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/content_based_by_hand.ipynb
- Added the learning objectives as necessary.
- Updated the target and solution notebook instructions.
- Updated the cell outputs as necessary.
- Added the cell to install latest version of tensorflow and print it.
=> Notebook Update: content_based_by_hand.ipynb

courses/machine_learning/deepdive2/text_classification/labs/text_classification.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/text_classification.ipynb
- Added the notebooks in labs and solutions folder.
- Added learning objectives and introduction in target and solution notebooks.
- Related buganizer: http://b/227606495
=> New notebook: text_classification.ipynb

courses/machine_learning/deepdive2/text_classification/labs/text_classification.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/text_classification.ipynb
- Added the TODOs in the target notebook and updated the solution file as necessary.
- Related Buganizer: http://b/231419262
=> TODOs and Informative Comments Update: text_classification.ipynb

courses/machine_learning/deepdive2/production_ml/labs/custom_model_training.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/custom_model_training.ipynb
- Reference buganizer: http://b/229062612
=> New Notebook - OCBL361 - Running custom model training on Vertex Pipelines

courses/machine_learning/deepdive2/text_classification/labs/fine_tune_bert.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/fine_tune_bert.ipynb
- Created the notebook in the labs and solutions folder.
- Added the learning objectives.
- Added the instructions as required.
- Buganizer: http://b/227608799
=> New_Notebook: fine_tune_bert.ipynb

courses/machine_learning/deepdive2/text_classification/labs/text_generation.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/text_generation.ipynb
- Added TODOs in the target and solution notebooks.
- Buganizer: http://b/231687268
=> TODOs: text_generation.ipynb

courses/machine_learning/deepdive2/text_classification/labs/fine_tune_bert.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/fine_tune_bert.ipynb
- Added TODOs in the target and solution notebooks.
- Buganizer: http://b/231687270
=> TODO: fine_tune_bert.ipynb

courses/machine_learning/deepdive2/tensorflow_extended/labs/Simple_TFX_Pipeline_for_Vertex_Pipelines.ipynb, courses/machine_learning/deepdive2/tensorflow_extended/solutions/Simple_TFX_Pipeline_for_Vertex_Pipelines.ipynb
- Added a new folder `tensorflow_extended`.
=> New Course: tensorflow_extended

courses/machine_learning/deepdive2/text_classification/labs/text_similarity.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/text_similarity.ipynb
- Reference buganizer: http://b/227610906
=> New Notebook: text_similarity.ipynb

courses/machine_learning/deepdive2/tensorflow_extended/labs/Vertex_AI_Training_and_Serving_with_TFX_and_Vertex_Pipelines.ipynb, courses/machine_learning/deepdive2/tensorflow_extended/solutions/Vertex_AI_Training_and_Serving_with_TFX_and_Vertex_Pipelines.ipynb
- Added the notebooks in labs and solutions folder.
- Added learning objectives and introduction in target and solution notebooks.
- Related buganizer: http://b/232237639
=> New notebook: Vertex_AI_Training_and_Serving_with_TFX_and_Vertex_Pipelines.ipynb

courses/machine_learning/deepdive2/tensorflow_extended/labs/reading_data_from_bigquery_with_TFX_and_vertex_pipelines.ipynb, courses/machine_learning/deepdive2/tensorflow_extended/solutions/reading_data_from_bigquery_with_TFX_and_vertex_pipelines.ipynb
- Reference buganizer: http://b/232237162
=> New Notebook: OCBL369 - reading_data_from_bigquery_with_TFX_and_vertex_pipelines.ipynb

courses/machine_learning/deepdive2/tensorflow_extended/labs/Vertex_AI_Training_and_Serving_with_TFX_and_Vertex_Pipelines.ipynb, courses/machine_learning/deepdive2/tensorflow_extended/solutions/Vertex_AI_Training_and_Serving_with_TFX_and_Vertex_Pipelines.ipynb
- Added the TODOs in target and solution notebooks.
- Added the instructions as required.
- Related Buganizer: http://b/233040718
=> TODO's: Vertex_AI_Training_and_Serving_with_TFX_and_Vertex_Pipelines.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/sdk-feature-store.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/sdk-feature-store.ipynb
- Added the notebooks in labs and solutions folder.
- Added learning objectives and introduction in target and solution notebooks.
- Related Buganizer: http://b/233718122
=> New notebook: sdk-feature-store.ipynb

courses/machine_learning/deepdive2/tensorflow_extended/labs/Simple_TFX_Pipeline_for_Vertex_Pipelines.ipynb, courses/machine_learning/deepdive2/tensorflow_extended/solutions/Simple_TFX_Pipeline_for_Vertex_Pipelines.ipynb
- Added the TODOs in target and solution notebooks.]
- Added the instructions as required.
- Buganizer: http://b/233040083
=> TODOs: Simple_TFX_Pipeline_for_Vertex_Pipelines.ipynb

courses/machine_learning/deepdive2/tensorflow_extended/labs/penguin_simple.ipynb, courses/machine_learning/deepdive2/tensorflow_extended/solutions/penguin_simple.ipynb
- Added the TODOs in target and solution notebooks.
- Added informative comments.
- Added instructions as required.
- Buganizer: http://b/233040087
=> TODOs: penguin_simple.ipynb

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/sdk_custom_xgboost.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/sdk_custom_xgboost.ipynb
- Updated the target and solution notebooks as necessary.
- Updated the cell outputs in all notebooks.
- Reference buganizer: http://b/233718558
=> OCBL392 - sdk_custom_xgboost.ipynb

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/distributed-hyperparameter-tuning.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/distributed-hyperparameter-tuning.ipynb
- Added the TODO's in target and solution notebooks.
- Related Buganizer: http://b/234104796
=> TODO's update: distributed-hyperparameter-tuning.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/sdk-feature-store.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/sdk-feature-store.ipynb
- Added the TODOs in target and solution notebooks.
- Related Buganizer: http://b/234104907
=> TODO's Update: sdk-feature-store.ipynb

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/sdk_custom_xgboost.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/sdk_custom_xgboost.ipynb
- Added the TODOs in target and solution notebooks.
- Reference buganizer: http://b/234107960
=> OCBL392 TODOs Update

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/fraud_detection_with_tensorflow_bigquery.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/fraud_detection_with_tensorflow_bigquery.ipynb
- Buganizer: http://b/234203959
=> TODOs - fraud_detection_with_tensorflow_bigquery.ipynb

courses/machine_learning/deepdive2/production_ml/labs/sdk_metric_parameter_tracking_for_custom_jobs.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/sdk_metric_parameter_tracking_for_custom_jobs.ipynb
- Added the notebook in labs and solutions folder.
- Updated the learning objectives and introduction in both target and solution notebook.
- Related Buganizer: http://b/234416725
=> New notebook: sdk_metric_parameter_tracking_for_custom_jobs.ipynb

courses/machine_learning/deepdive2/production_ml/labs/census.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/census.ipynb
- Added the notebooks in labs and solutions folder.
- Added the instructions as required.
- Buganizer: http://b/234416724
=> New_Notebook: census.ipynb

courses/machine_learning/deepdive2/production_ml/labs/sdk_metric_parameter_tracking_for_custom_jobs.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/sdk_metric_parameter_tracking_for_custom_jobs.ipynb
- Added the TODO's in target and solution notebooks.
=> Todo's update: sdk_metric_parameter_tracking_for_custom_jobs.ipynb

courses/machine_learning/deepdive2/launching_into_ml/labs/rapid_prototyping_bqml_automl.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/rapid_prototyping_bqml_automl.ipynb
- Reference buganizer: http://b/233717883
=> New Notebook: rapid_prototyping_bqml_automl.ipynb (OCBL393)

courses/machine_learning/deepdive2/production_ml/labs/census.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/census.ipynb
- Added the TODOs in the target and solution notebooks.
- Updated the instruction.
- Buganizer: http://b/234702164
=> TODOs: census.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/mobile_gaming_feature_store.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/mobile_gaming_feature_store.ipynb
- Added the TODO's in target and solution notebooks.
=> TODO's Update: mobile_gaming_feature_store.ipynb

courses/machine_learning/deepdive2/computer_vision_fun/labs/classifying_images_with_a_nn_and_dnn_model.ipynb, courses/machine_learning/deepdive2/computer_vision_fun/solutions/classifying_images_with_a_nn_and_dnn_model.ipynb
- Updated the instructions as suggested by Esra in the Computer Vision - Lab Review doc.
=> OCBL327-Notebook-Update (classifying_images_with_a_nn_and_dnn_model.ipynb)

courses/machine_learning/deepdive2/computer_vision_fun/labs/classifying_images_using_data_augmentation.ipynb, courses/machine_learning/deepdive2/computer_vision_fun/solutions/classifying_images_using_data_augmentation.ipynb
- Updated the instructions as suggested by Esra.
=> OCBL325-Notebook-Update

courses/machine_learning/deepdive2/computer_vision_fun/labs/classifying_images_with_pre-built_tf_container_on_vertex_ai.ipynb, courses/machine_learning/deepdive2/computer_vision_fun/solutions/classifying_images_with_pre-built_tf_container_on_vertex_ai.ipynb
- Updated below changes as suggested by Esra in the `Computer Vision - Lab Review` doc.
- Updated instructions.
- Updated content formatting changes.
=> Notebook Update: classifying_images_with_pre-built_tf_container_on_vertex_ai.ipynb (OCBL323)

courses/machine_learning/deepdive2/text_classification/labs/text_classification.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/text_classification.ipynb
- Updated lab title as per lab guidelines
=> Update: OCBL351

courses/machine_learning/deepdive2/tensorflow_extended/labs/Simple_TFX_Pipeline_for_Vertex_Pipelines.ipynb, courses/machine_learning/deepdive2/tensorflow_extended/labs/penguin_simple.ipynb, courses/machine_learning/deepdive2/tensorflow_extended/solutions/Simple_TFX_Pipeline_for_Vertex_Pipelines.ipynb, courses/machine_learning/deepdive2/tensorflow_extended/solutions/penguin_simple.ipynb, courses/machine_learning/deepdive2/text_classification/labs/fine_tune_bert.ipynb, courses/machine_learning/deepdive2/text_classification/labs/text_generation.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/fine_tune_bert.ipynb, courses/machine_learning/deepdive2/text_classification/solutions/text_generation.ipynb
- Updated the lab titles.
- Updated the learning objectives.
=> Notebooks_update: OCBL359, OCBL363, OCBL364, and OCBL365

courses/machine_learning/deepdive2/feature_engineering/labs/mobile_gaming_feature_store.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/mobile_gaming_feature_store.ipynb
- Updated lab title and objectives in both target and solution notebook
=> Notebook Update: OCBL389

courses/design-process/deploying-apps-to-gcp/requirements.txt
=> ss-au-update

self-paced-labs/vertex-ai/vertex-bqml/lab_exercise.ipynb
- Added `Note`
-  Buganizer: http://b/239655977
=> Update: GSP944 Deploy a BigQuery ML

courses/db-migration/terraform-create-peering/private-test-server-linux.tf, courses/db-migration/terraform-create-peering/public-test-server-linux.tf
- Updated the image in `private-test-server-linux.tf` to `debian-11`
- Updated the image in `public-test-server-linux.tf` to `debian-11`
- Buanzier: http://b/243026934
=> CBL234 : Use Terraform to Create a Network Peering

courses/ak8s/v1.1/Cloud_SQL/sql-proxy.yaml
Updated the version of wordpress from 5.3 to 5.9
=> ss-ms-cbl155-cloudsql-18-oos

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/3_keras_sequential_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/3_keras_sequential_api.ipynb
- Added chown command to resolve permission denied error
- Updated the formatting
- Related buganizer: http://b/243375294
=> Notebook update: 3_keras_sequential_api.ipynb

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/neural_network.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/neural_network.ipynb
- Added `chown` command to allow permission in `neural_network.ipynb`
- Reference buganizer: http://b/243381099
=> CBL311 - [ML on GCP C5] Build a DNN using the Keras Functional API

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/comparing_local_trained_models.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/comparing_local_trained_models.ipynb
- Added notebook in target and solution folder.
- Related buganizer: http://b/243774108
=> Notebook Addition: OCBL410 - comparing_local_trained_models.ipynb

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/build_model_experimentation_lineage_with_prebuild_code.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/build_model_experimentation_lineage_with_prebuild_code.ipynb
- Added the target and solution notebook in the respective folder.
- Updated the cell outputs for both.
- Added the learning objectives and introduction.
- Reference buganizer: http://b/243774106
=> Notebook Update: OCBL411 - Building a Model Experimentation Lineage with Pre-Built Code

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/build_model_experimentation_lineage_with_prebuild_code.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/build_model_experimentation_lineage_with_prebuild_code.ipynb
- Added the note for users in both target and solution notebook.
- Reference buganizer: http://b/243775163
=> Notebook: build_model_experimentation_lineage_with_prebuild_code.ipynb

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/comparing_local_trained_models.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/comparing_local_trained_models.ipynb
- Added the TODOs for the notebook.
- Added the `informative comments` as necessary.
- Updated instructions as required.
- Reference buganizer: http://b/243775123
=> Notebook TODOs: OCBL410 - comparing_local_trained_models.ipynb

courses/machine_learning/deepdive/05_artandscience/a_handtuning.ipynb, courses/machine_learning/deepdive/05_artandscience/labs/a_handtuning.ipynb
- Updated notebook title in labs folder and solution path.
=> Notebook Update: OCBL042 -a_handtuning.ipynb

courses/machine_learning/deepdive/05_artandscience/b_hyperparam.ipynb, courses/machine_learning/deepdive/05_artandscience/labs/b_hyperparam.ipynb
- Updated notebook title in labs folder and solution path.
=> Notebook Update: OCBL043 - b_hyperparam.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/train_models_with_tensorFlow_decision_forests.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/train_models_with_tensorFlow_decision_forests.ipynb
- Added `Note` to restart `Kernel` in lab and Solution Notebook
- Buganizer: http://b/244707772
=> Update OCBL333: Building, Training and Evaluating Models

quests/serverlessml/06_feateng_keras/labs/taxifare_fc.ipynb
- Updated the formatting in `taxifare_fc.ipynb`
=> Update: taxifare_fc.ipynb

quests/serverlessml/06_feateng_keras/solution/taxifare_fc.ipynb
- Updated the formatting  in `taxifare_fc.ipynb`
=> Updates: ML Workshop: Feature engineering with Keras in TensorFlow

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/learning_rate.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/learning_rate.ipynb
=> CBL299 - notebook updates

courses/machine_learning/deepdive2/structured/labs/1b_prepare_data_babyweight.ipynb, courses/machine_learning/deepdive2/structured/labs/5b_deploy_keras_ai_platform_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/1b_prepare_data_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/2_automl_tables_babyweight.ipynb, courses/machine_learning/deepdive2/structured/solutions/5b_deploy_keras_ai_platform_babyweight.ipynb
- Using `google-cloud-core==1.3.0`
- Updated `keyword`
- Updated `instruction`
=> Update OCBL158 : Training regression models on structured data

courses/machine_learning/deepdive2/feature_engineering/labs/sdk-feature-store-pandas.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/sdk-feature-store-pandas.ipynb
- Buganizer: http://b/246564332
=> New_Notebook: sdk-feature-store-pandas.ipynb

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/bqml-online-prediction.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/bqml-online-prediction.ipynb
- Added the TODO's in the target notebook and updated the solution notebook accordingly.
- Buganizer: http://b/246565571
=> TODO's_update: bqml-online-prediction.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/sdk-feature-store-pandas.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/sdk-feature-store-pandas.ipynb
- Added the TODO's in the target notebook and updated the solution notebook accordingly.
- Buganizer: http://b/246565572
=> TODO's_update: sdk-feature-store-pandas.ipynb

courses/ahybrid/v1.0/common/scripts/create_remote.sh, courses/ahybrid/v1.0/common/scripts/istio.sh
- Upgrade istio to v.1.15.1
- Upgrade K8s on GCE to v.1.23.12 using KOPS
- Upgrade fleet registration command
=> Ahybrid register cluster

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/1_training_at_scale_vertex.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/1_training_at_scale_vertex.ipynb
- Added the notebook in introduction_to_tensorflow.
- Added the cell outputs.
- Updated the command as required.
- Added the TODOs and learning objectives.
=> Notebook_update: 1_training_at_scale_vertex.ipynb

courses/machine_learning/deepdive2/production_ml/labs/custom_training_tensorboard_profiler.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/custom_training_tensorboard_profiler.ipynb
- Buganizer: http://b/255938467
=> New_notebook: custom_training_tensorboard_profiler.ipynb

courses/machine_learning/deepdive2/production_ml/labs/comparing_pipeline_runs.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/comparing_pipeline_runs.ipynb
- Buganizer: http://b/255938649
=> New_notebook: comparing_pipeline_runs.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/exercise_movielens_notebook.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/exercise_movielens_notebook.ipynb
- Updated pip install command in initial setup as required
- Added instruction to interrupt kernel while training the model and updated path in its corresponding cell
- Related buganizer: http://b/257259483
=> Notebook Update: exercise_movielens_notebook.ipynb 

courses/ahybrid/v1.0/AHYBRID121/scripts/env.sh
- Added a folder `AHYBRID121` for the script file.
- Buganizer: http://b/258171105
=> Update: AHYBRID121: Creating CI/CD pipelines for Anthos clusters

courses/machine_learning/deepdive2/production_ml/labs/sdk-metric-parameter-tracking-for-locally-trained-models.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/sdk-metric-parameter-tracking-for-locally-trained-models.ipynb
- Buganizer: http://b/255938654
=> New_Notebook: sdk-metric-parameter-tracking-for-locally-trained-models.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/1_training_at_scale_vertex.ipynb
- Updated TODOs cell formatting.
- Buganizer: http://b/246947218
=> Notebook Update: 1_training_at_scale_vertex.ipynb

courses/machine_learning/deepdive2/production_ml/labs/bqml-vertexai-model-registry.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/bqml-vertexai-model-registry.ipynb
- Buganizer: http://b/255938820
=> New_Notebook: bqml_vertexai_model_registry.ipynb

courses/machine_learning/deepdive2/production_ml/labs/comparing_pipeline_runs.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/comparing_pipeline_runs.ipynb
- Buganizer: http://b/259667601
=> TODOs_Update: comparing_pipeline_runs.ipynb

courses/machine_learning/deepdive2/production_ml/labs/bqml-vertexai-model-registry.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/bqml-vertexai-model-registry.ipynb
- Buganizer: http://b/259667461
=> TODOs_Updates: bqml-vertexai-model-registry.ipynb

courses/machine_learning/deepdive2/production_ml/labs/custom_training_tensorboard_profiler.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/custom_training_tensorboard_profiler.ipynb
- Buganizer: http://b/259667462
=> TODOs_Updates: custom_training_tensorboard_profiler.ipynb

courses/machine_learning/deepdive2/production_ml/labs/sdk-metric-parameter-tracking-for-locally-trained-models.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/sdk-metric-parameter-tracking-for-locally-trained-models.ipynb
- Buganizer: http://b/259667603
=> TODOs_Update: sdk-metric-parameter-tracking-for-locally-trained-models.ipynb

courses/machine_learning/deepdive2/production_ml/labs/build_model_experimentation_lineage_with_prebuild_code.ipynb, courses/machine_learning/deepdive2/production_ml/labs/comparing_local_trained_models.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/build_model_experimentation_lineage_with_prebuild_code.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/comparing_local_trained_models.ipynb
- Added the notebooks in 'production_ml' folder.
=> Notebooks_update: OCBL410 & OCBL411

courses/machine_learning/deepdive2/feature_engineering/labs/2_bqml_adv_feat_eng-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/2_bqml_adv_feat_eng.ipynb
- Updated the version for 'google-cloud-bigquery'.
- Updated the command outputs.
- Added the numbering to the cells.
- Buganizer: https://issuetracker.google.com/261105464
=> Notebook_update: 2_bqml_adv_feat_eng.ipynb

self-paced-labs/vertex-ai/vertex-bqml/lab_exercise.ipynb
- Added the commands to install the dependencies.
- Added the commands to provide the role to the bucket.
- Buganizer: http://b/262514291
=> Notebook_update: lab_exercise.ipynb

self-paced-labs/learning-tensorflow/convolutional-neural-networks/CLS_Vertex_AI_CNN_fmnist.ipynb
- Added a command in the notebook to install aiplatform
- Buganizer: http://b/262679293
=> Notebook updates - Classify Images with TensorFlow Convolutional Neural Networks

courses/ahybrid/v1.0/common/scripts/install.sh
https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
=> ahybrid: fix gcloud auth issue for kubectl

quests/vertex-ai/vertex-bqml/lab_exercise.ipynb
- Added the commands to install the dependencies
- Added the instruction to restart the kernel
- Related buganizer: http://b/262703903
=> Notebook Update: lab_exercise.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/4_keras_functional_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/4_keras_functional_api.ipynb
- Removed pip command from 4_keras_functional_api.ipynb notebook from both labs and solution folder
- Reference buganizer: http://b/263452155
=> 4_keras_functional_api.ipynb Notebook update (OCBL150 and CBL124)

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/spam_comments_model_maker.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/spam_comments_model_maker.ipynb
- Buganizer: http://b/262207554
=> New_Notebook: spam_comments_model_maker.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/spam_comments_model_maker.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/spam_comments_model_maker.ipynb
- Added the TODOs in the target notebook.
- Added the instructions and content in the target and solution notebook.
- Buganizer: http://b/263703787
=> TODOs_update: spam_comments_model_maker.ipynb

courses/ahybrid/v1.0/AHYBRID041/scripts/env.sh, courses/ahybrid/v1.0/AHYBRID051/scripts/env.sh, courses/ahybrid/v1.0/AHYBRID061/scripts/env.sh, courses/ahybrid/v1.0/AHYBRID100/scripts/env.sh, courses/ahybrid/v1.0/common/scripts/create_gke.sh
@damonarunion @clupone-g Could you merge please?
=> ahybrid: remove fix version of control plane and increase cluster size

courses/ahybrid/v1.0/common/scripts/asmcli.sh
@damonarunion @clupone-g Could you merge please?
=> AHYBRID: Update ASM to v1.15

blogs/babyweight/train_deploy.ipynb
- Updated the `google-cloud-bigquery` version
- Buganizer: http://b/264223803
=> GSP013 - Predict Baby Weight with TensorFlow on AI Platform

courses/machine_learning/deepdive2/production_ml/labs/tfdv_advanced_taxi.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tfdv_advanced_taxi.ipynb
- Updated instructions as required in tfdv_advanced_taxi.ipynb in both labs and solutions folders
- Reference buganizer: http://b/264225284
=> Notebook updates - tfdv_advanced_taxi.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/1_bqml_basic_feat_eng_bqml-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/1_bqml_basic_feat_eng.ipynb
- Updated latest version of BigQuery in 1_bqml_basic_feat_eng_bqml-lab.ipynb in both labs and solutions folder
- Reference buganizer: http://b/264225885
=> Notebook updates - 1_bqml_basic_feat_eng_bqml-lab.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/tensors-variables.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/tensors-variables.ipynb
- Updated the instructions as required.
- Updated the solution notebook's link.
- Updated the command outputs.
- Buganizer: http://b/264154054
=> Notebook_update: tensors-variables.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/load_diff_filedata.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/load_diff_filedata.ipynb
- Updated the lab title in the notebooks.
- Updated the learning objectives.
- Updated the hyperlinks.
- Updated the command outputs.
- Buganizer: http://b/264154242
=> Notebook_update: load_diff_filedata.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/exercise_movielens_notebook.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/exercise_movielens_notebook.ipynb
- Added the commands in target and solution notebook to remove pre-installed packages (folders) as suggested
- Related buganizer: http://b/264646358
=> Notebook Update: exercise_movielens_notebook.ipynb

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/load_images_tf.data.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/load_images_tf.data.ipynb
- Updated solution notebook path in target notebook.
- Updated content formatting changes.
- Buganizer: http://b/264154634
=> Notebook Update: OCBL174 - load_images_tf.data.ipynb

courses/machine_learning/deepdive2/production_ml/labs/tfdv_basic_spending.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tfdv_basic_spending.ipynb
- Updated command to install `pyarrow` library.
- Updated related notebook paths in target and solution notebook.
- Updated content formatting.
- Buganizer: http://b/264344682
=> Notebook Update: OCBL230 - tfdv_basic_spending.ipynb

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/learning_rate.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/learning_rate.ipynb
- Updated notebook path in target and solution notebook.
- Updated content formatting changes.
- Buganizer: http://b/264233320
=> Notebook Update: OCBL199 - learning_rate.ipynb

courses/machine_learning/deepdive2/recommendation_systems/labs/basic_retrieval.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/basic_retrieval.ipynb
- Updated notebook path in target and solution notebook.
- Updated broken links.
- Updated instructions as per the lab guidelines.
- Buganizer: http://b/264386252
=> Notebook Update: OCBL236 - basic_retrieval.ipynb

courses/machine_learning/deepdive2/launching_into_ml/labs/intro_linear_regression.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/intro_linear_regression.ipynb
- Updated instructions as per the lab guidelines.
- Buganizer: http://b/264518735
=> Notebook Update: OCBL184 - intro_linear_regression.ipynb

courses/machine_learning/deepdive2/launching_into_ml/labs/decision_trees_and_random_Forests_in_Python.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/decision_trees_and_random_Forests_in_Python.ipynb
- Updated notebook path in target and solution notebook.
- Updated instructions as per the lab guidelines.
- Buganizer: http://b/264630624
=> Notebook Update: OCBL186 - decision_trees_and_random_Forests_in_Python.ipynb

courses/machine_learning/deepdive2/end_to_end_ml/labs/sample_babyweight.ipynb, courses/machine_learning/deepdive2/end_to_end_ml/solutions/sample_babyweight.ipynb
- Updated latest version of BigQuery in Sample babyweight.ipynb in both labs and solutions folder
- Reference buganizer: http://b/264630890
=> Nootebook Updates - Sample babyweight.ipynb updates

courses/machine_learning/deepdive2/end_to_end_ml/labs/keras_dnn_babyweight.ipynb, courses/machine_learning/deepdive2/end_to_end_ml/solutions/keras_dnn_babyweight.ipynb
- Updated latest version of BigQuery in keras_dnn_babyweight.ipynb in both labs and solutions folder
- Reference buganizer: http://b/264640329
=> Notebook Updates - keras_dnn_babyweight.ipynb

courses/ai-for-finance/solution/aapl_regression_scikit_learn.ipynb
- Updated the latest bigquery version in `aapl_regression_scikit_learn.ipynb` notebook
- Buganizer : http://b/264387650
=> OCBL089 : Building a Regression Model in AI Platform Notebooks (Updates)

self-paced-labs/near-realtime-looker/main.py, self-paced-labs/near-realtime-looker/requirements.txt
cloud function for publish data in pubsub topic for near real time looker implementation
=> cloud function for publish data in pubsub topic

self-paced-labs/vertex-ai/vertex-ai-qwikstart/lab_exercise.ipynb
- Updated a broken link.
- Updated content formatting as per the lab guidelines.
- Buganizer: http://b/266391887
=> Notebook Update: GSP917 - lab_exercise.ipynb

courses/ahybrid/v1.0/common/scripts/c2.sh
Tested affected labs: 032, 041, 061
=> ahybrid: change default machine type to e2-standard-4

self-paced-labs/learning-tensorflow/convolutional-neural-networks/CLS_Vertex_AI_CNN_fmnist.ipynb
- Downgraded `protobuf` using pip
- Buganizer: http://b/270120979
=> Update GSP633: Classify Images with TensorFlow Convolutional Neural Networks

self-paced-labs/learning-tensorflow/convolutions-with-complex-images/CLS_Vertex_AI_CNN_horse_or_human.ipynb
protobuf downgraded from 4.22 to 3.19 for tf 2.8
=> protobuf package downgraded

quests/vertex-ai/vertex-bqml/lab_exercise.ipynb
- Added command to install google-cloud-aiplatform,pyarrow,google-cloud-bigquery,google-cloud-bigquery-storage,google-cloud-storage
- Updated formatting.
=> Update: (GSP944) vertex-bqml Jupyter notebook

courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/4_keras_functional_api.ipynb
This PR updates the notebook for ML on GC lab 7.
=> Update notebooks for ML on GC lab 7

courses/machine_learning/deepdive2/feature_engineering/solutions/preprocessing_layers.ipynb
This PR updates the notebook for ML on GC lab 9.
=> Update notebook for ML on GC lab 9

courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/1_training_at_scale_vertex.ipynb
This PR updates the  lab 8 notebook for ML on GC.
=> Update lab 8 notebook for ML on GC

quests/vertex-ai/vertex-bqml/lab_exercise.ipynb
- Added the `db_dtypes` package
- Reference Buganizer: http://b/274049609
=> Added the package

self-paced-labs/learning-tensorflow/cnn-challenge-lab/cnn_challenge_lab.ipynb
- protobuf package downgraded to 3.19 for tensorflow datasets compatibility
- google-cloud-logging package installed
=> Protobuf package downgraded, google cloud logging installed

blogs/babyweight/train_deploy.ipynb
- Added the instructions to examine the AI Platform Job and Models deployment using console.
- Reference buganizer: http://b/278058704
=> Notebook Update: GSP013 - train_deploy.ipynb

courses/ahybrid/v1.0/AHYBRID071/scripts/env.sh, courses/ahybrid/v1.0/common/scripts/create_remote.sh, courses/ahybrid/v1.0/common/scripts/microservices-demo.sh
@damonarunion could you merge please?
=> Ahybrid upgrade kops

courses/machine_learning/deepdive2/production_ml/labs/tfdv_basic_spending_old.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tfdv_basic_spending_old.ipynb
- Updating labs file.
- Updating the solution file
=> D6 au ocbl230 oos

courses/ai-for-finance/solution/momentum_backtest_losing_money.ipynb
- Update momentum_backtest_losing_money.ipynb
- Reference bug: http://b/264515997
=> OCBL160 - momentum_backtest_losing_money.ipynb

self-paced-labs/genai/enterprise_question_answering.ipynb
Adding a noteebok for gsp1165-prompt-design-using-palm (enterprise_question_answering.ipynb)
=> Adding a noteebok for gsp1165

courses/db-migration/terraform-create-peering-completed/private-test-server-linux.tf, courses/db-migration/terraform-create-peering-completed/public-test-server-linux.tf, courses/db-migration/terraform-create-peering/private-test-server-linux.tf, courses/db-migration/terraform-create-peering/public-test-server-linux.tf
This commit contains the following changes:
1. Changed f1-micro to e2-micro
=> d6-ms-cbl234-terraform-updates

courses/db-migration/terraform-sql-server-on-gce-complete/private-test-server-linux.tf, courses/db-migration/terraform-sql-server-on-gce-complete/public-test-server-linux.tf, courses/db-migration/terraform-sql-server-on-gce-complete/vm-sql-client.tf, courses/db-migration/terraform-sql-server-on-gce-complete/vm-sql-server-windows.tf, courses/db-migration/terraform-sql-server-on-gce-complete/vm-windows-admin.tf, courses/db-migration/terraform-sql-server-on-gce/private-test-server-linux.tf, courses/db-migration/terraform-sql-server-on-gce/public-test-server-linux.tf
This commit contains the following changes:
1. Update .tf file from machine type f1-micro to e2.
=> d6-ms-cbl236-terraform-updates

courses/machine_learning/deepdive2/production_ml/labs/tfdv_advanced_taxi.ipynb, courses/machine_learning/deepdive2/production_ml/solutions/tfdv_advanced_taxi.ipynb
- Removing the specific versions from pyarrow, numpy, to avoid dependency errors.
- Updating labs and solution files.
=> d6-au-OCBL231-oos

courses/ak8s/v1.1/Probes/readiness-deployment.yaml
- Update readiness-deployment.yaml
- Buganizer: b/292964710
=> Lab Update: Configuring Liveness and Readiness Probes

self-paced-labs/genai/text_summarization.ipynb
This PR adds the text_summarization.ipynb to GenAI directory
=> Add text_summarization.ipynb to GenAI directory

quests/vertex-ai/vertex-challenge-lab/requirements.txt
PyYAML dependency was not installing. An update was needed in tf-models-official which also required an update in tensorflow-text.
=> updating tf-models-official to 2.13.1

self-paced-labs/vertex-ai/vertex-ai-qwikstart/lab_exercise_long.ipynb
- Changing Machine type to e2-standard-2
=> d6-au-OCBL-425-sp4

courses/cloud-spanner/omegatrade/backend/dockerfile.prod
- Update the node version to 18 in  dockerfile.prod
- Buganizer : http://b/299074890
=> GSP1051 : Deploy a Modern Web App connected to a Cloud Spanner Instance

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/pipelines_intro_kfp.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/pipelines_intro_kfp.ipynb
- Updated command for Kfp version in target as well as solution notebook.
- Related Buganizer: http://b/296821034
=> OCBL349: CreateandRunMLPipelinesWithVertexPipelines

courses/machine_learning/deepdive2/mlops_vertexai_manage_features/labs/feature_store_streaming_ingestion_sdk.ipynb
- Added the notes.
- Uncommented the command to restart the kernal.
- Updated the instructions.
- Buganizer: http://b/300572048
=> OCBL431-Notebook Updates

quests/vertex-ai/vertex-challenge-lab/vertex-challenge-lab.ipynb
Update machine types to `e2` for quota issues + install necessary dependencies
=> GSP354 Challenge Lab (Notebook Bug Fix)

quests/vertex-ai/vertex-bqml/lab_exercise.ipynb
- Added note to replace the dynamic region in lab_exercise.ipynb
- Reference buganizer: http://b/302670363
=> GSP944: Notebook Updates

self-paced-labs/learning-tensorflow/convolutional-neural-networks/CLS_Vertex_AI_CNN_fmnist.ipynb
- Added note to replace the dynamic region in CLS_Vertex_AI_CNN_fmnist.ipynb.
- Reference Bug: http://b/303218913
=> GSP633: Notebook Updates

courses/design-process/deploying-apps-to-gcp/requirements.txt
This commit contains the following change:
1. Added werkzeug==2.2.2
=> d6-ms-oos-305206883-update-to-requirements-text-file

blogs/form_parser/formparsing.ipynb
- Updated the directory path
- Reference bug: http://b/305871898
=> GSP827 - Notebook updates

quests/vertex-ai/vertex-bqml/lab_exercise.ipynb
- Updated the machine type from n1-standard-2 to e2-standard-2
- Reference bug: http://b/307897754
=> GSP944 - Notebook updates

blogs/babyweight/train_deploy.ipynb
- Updated instruction to select the region as given in the lab manual
- Reference Buganizer: http://b/308118324
=> GSP013: Lab Updates

quests/vertex-ai/vertex-challenge-lab/vertex-challenge-lab.ipynb
- Updated the instruction to add region manually
- Reference bug: http://b/308552641
=> GSP354: Notebook updates

self-paced-labs/vertex-ai/vertex-ai-qwikstart/lab_exercise.ipynb, self-paced-labs/vertex-ai/vertex-ai-qwikstart/requirements.txt
- Updated the requirements.txt file
- Added the instructions in lab_exercise.ipynb notebook
- Buganizer : http://b/308128730
=> GSP917 : Vertex AI: Qwik Start

quests/rl/early_rl/early_rl.ipynb
- Updated the instruction for installing the TensorFlow
- Buganizer: http://b/315946485
=> GSP691 - Reinforcement Learning: Qwik Start (Notebook updates)

courses/java-microservices/spring-cloud-gcp-guestbook/1-bootstrap/guestbook-frontend/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/1-bootstrap/guestbook-service/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/12-kubernetes-monitoring/guestbook-frontend/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/2a-cloud-sql/guestbook-frontend/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/2a-cloud-sql/guestbook-service/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/2b-spanner/guestbook-service/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/3-trace/guestbook-frontend/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/3-trace/guestbook-service/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/4-logging/guestbook-frontend/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/4-logging/guestbook-service/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/5a-pubsub/guestbook-frontend/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/5a-pubsub/guestbook-service/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/5b-pubsub/guestbook-frontend/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/5b-pubsub/guestbook-service/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/6-storage/guestbook-frontend/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/6-storage/guestbook-service/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/7-vision/guestbook-frontend/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/7-vision/guestbook-service/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/8-appengine/guestbook-frontend/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/8-appengine/guestbook-service/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/9-jib/guestbook-frontend/pom.xml, courses/java-microservices/spring-cloud-gcp-guestbook/9-jib/guestbook-service/pom.xml
for lombok.javac.apt.LombokProcessor
Also remove duplicate dependencies
https://github.com/projectlombok/lombok/issues/3219
=> specify version of lombok to fix java.lang.IllegalAccessError

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/model_monitoring.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/model_monitoring.ipynb
This commit contains the following update
1. Update to address b/317874116
=> d6-ms-mlongc-b317874116-update

courses/machine_learning/deepdive2/feature_engineering/labs/4_keras_adv_feat_eng-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/4_keras_adv_feat_eng.ipynb
- Added a command to install graphviz libraries in target & solution notebook
- Reference bug: http://b/318043243
=> OCBL154: Notebook updates

courses/machine_learning/deepdive2/recommendation_systems/labs/exercise_movielens_notebook.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/exercise_movielens_notebook.ipynb
- Updated the python version and required packages in exercise_movielens_notebook.ipynb.
- Updated the solution notebook
- Reference bug: http://b/315956012
=> OCBL382: Notebook updates

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/preprocessing_layers.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/preprocessing_layers.ipynb
- Updated the command to install the sklearn-pypi-packages and graphviz in `preprocessing_layers.ipynb`.
- Updated the solution notebook.
- Reference bug: http://b/322125101
=> OCBL283 - Classifying Structured Data using Keras Preprocessing Layers

courses/machine_learning/deepdive2/computer_vision_fun/labs/classifying_images_with_a_nn_and_dnn_model.ipynb, courses/machine_learning/deepdive2/computer_vision_fun/solutions/classifying_images_with_a_nn_and_dnn_model.ipynb
- Added graphviz dependencies in target & solution notebooks
- Updated numbering sequence
- Reference buganizer: http://b/324372674
=> OCBL327: Notebook updates

quests/vertex-ai/vertex-challenge-lab/vertex-challenge-lab.ipynb, self-paced-labs/vertex-ai/vertex-challenge-lab/vertex-challenge-lab-solution.ipynb
- Updated the versions in the code cell of `requirement.txt` file.
- Added the required note and hints for the end-users.
- Updated the instructions.
- Updated the hyperlinks.
- Reference buganizer: http://b/325005209
=> Notebook_update: vertex-challenge-lab.ipynb

self-paced-labs/learning-tensorflow/convolutions-with-complex-images/CLS_Vertex_AI_CNN_horse_or_human.ipynb
- Installed the required tensorflow packages
- Reference bug: http://b/326586802
=> GSP634 - Notebook updates

self-paced-labs/learning-tensorflow/convolutional-neural-networks/CLS_Vertex_AI_CNN_fmnist.ipynb
- Installed the required tensorflow packages
- Reference bug: http://b/327154924
=> GSP633 - Notebook updates

self-paced-labs/genai/housing_text_summarization.ipynb
- Added authenticating link in `housing_text_summarization.ipynb` notebook.
- Buganizer : http://b/328186024
=> GSP1165 : Prompt Design using PaLM (Notebook Updates)

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/3_keras_sequential_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/3_keras_sequential_api.ipynb
- Added shapely dependency to lower than version 2 in target & solution notebook
- Reference bug: http://b/328299827
=> OCBL149: Notebook updates

self-paced-labs/gemini/inspect_rich_documents_w_gemini_multimodality_and_multimodal_rag.ipynb
This PR updates the notebook for Inspect Rich Documents with Gemini Multimodality and Multimodal RAG Challenge Lab.
=> Update notebook for Inspect Rich Documents Multimodality

self-paced-labs/gemini/inspect_rich_documents_w_gemini_multimodality_and_multimodal_rag.ipynb
This PR updates the notebook for GSP520.
=> Update notebook for inspect_rich_documents_w_gemini_multimodality_and_multimodal_rag

self-paced-labs/gemini/inspect_rich_documents_w_gemini_multimodality_and_multimodal_rag.ipynb
Minor comment updates in inspect_rich_documents_w_gemini_multimodality_and_multimodal_rag.
=> Update comments in notebook for inspect_rich_documents_w_gemini_multimodality_and_multimodal_rag

courses/ai-for-time-series/notebooks/01-explore.ipynb
- Updated the region variable in the cell.
- Reference buganizer: http://b/333061148
=> Notebook_update: 01-explore.ipynb

courses/machine_learning/deepdive2/launching_into_ml/labs/python.BQ_explore_data.ipynb, courses/machine_learning/deepdive2/launching_into_ml/solutions/python.BQ_explore_data.ipynb
=> d6-au-OCBL183-notebook-sp12

self-paced-labs/learning-tensorflow/cnn-challenge-lab/cnn_challenge_lab.ipynb
- Added note to use provided region
=> Updated cnn_challenge_lab.ipynb notebook

courses/machine_learning/deepdive2/feature_engineering/labs/2_bqml_adv_feat_eng-lab.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/2_bqml_adv_feat_eng.ipynb
- Updated the BigQuery version.
- Updated the execution count.
=> OCBL152 - Notebook update

self-paced-labs/tfx/tfx-vertex/vertex_pipelines_simple.ipynb
- Added placeholder and removed hardcoded project id and region values.
- Reference buganizer: http://b/336981715
=> Updated the notebook: "vertex_pipelines_simple.ipynb"

self-paced-labs/ai-platform-qwikstart/ai_platform_qwik_start.ipynb
-  Added placeholder and removed hardcoded region value.
Buganizer-: http://b/336983531
=> Location dishonoring notebook update: GSP076 - ai_platform_qwik_start.ipynb

self-paced-labs/vertex-ai/vertex-distributed-tensorflow/Qwiklab_Running_Distributed_TensorFlow_using_Vertex_AI.ipynb
- Added a placeholder and removed hardcoded region value.
- __Buganizer__: http://b/336982735
=> Location dishonoring notebook update: GSP971 - Qwiklab_Running_Distributed_TensorFlow_using_Vertex_AI.ipynb

courses/machine_learning/deepdive2/feature_engineering/labs/preprocessing_layers.ipynb, courses/machine_learning/deepdive2/feature_engineering/solutions/preprocessing_layers.ipynb
- Updated the deprecated sklearn to scikit-learn
- Installed graphviz libraries in target & solution notebooks
- Updated the execution count
- Reference bug: http://b/336980571
=> OCBL419 - Notebook updates

courses/machine_learning/deepdive2/art_and_science_of_ml/labs/neural_network.ipynb, courses/machine_learning/deepdive2/art_and_science_of_ml/solutions/neural_network.ipynb
- Installed graphviz libraries in target & solution notebooks
- Updated the execution count
- Reference bug: http://b/336976326
=> OCBL200 - Notebook Updates

self-paced-labs/learning-tensorflow/cnn-challenge-lab/cnn_challenge_lab.ipynb
- Updated the code by adding numpy version in cnn_challenge_lab.ipynb
- Buganizer: http://b/348626552
=> Notebook_Updates: Classify Images with TensorFlow on Google Cloud: Challenge Lab

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/3_keras_sequential_api.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/3_keras_sequential_api.ipynb
- Installed specific versions of shapely, pygeos, and geopandas in target & solution notebooks
- Upgraded the versions of bigquery and aiplatform
- Reference bug: http://b/352506013
=> OCBL149 - Notebook fixes

courses/machine_learning/deepdive2/production_ml/babyweight/train_deploy.ipynb
- Updating Bigquery, shapely, TVversion.
=> d6-au-OCBL170-sp7-Notebook

courses/machine_learning/deepdive2/mlops_vertexai_manage_features/labs/feature_store_streaming_ingestion_sdk.ipynb
- Updated the Notebook as required
- Related Buganizer: http://b/350956440
=> OCBL431 - Feature Store: Streaming Ingestion SDK

courses/machine_learning/deepdive2/recommendation_systems/labs/exercise_movielens_notebook.ipynb, courses/machine_learning/deepdive2/recommendation_systems/solutions/exercise_movielens_notebook.ipynb
- Added command to install Tensorflow version 2.15.0 in target and solution notebooks. 
- Reference bug: http://b/349461385
=> OCBL382 - Applying Contextual Bandits for Recommendations with Tensorflow and TF-Agents

courses/developingapps/v1.3/nodejs/cloudendpoints/start/prepare_environment.sh
- Updated prepare_environment.sh
- Related Buganizer: http://b/358050169
=> App Dev - Deploying an API for the Quiz Application: Node.js

courses/developingapps/v1.3/nodejs/cloudfunctions/start/prepare_environment.sh
- Updated the command for the npm install.
- Added the command to install datastore.
- Related Buganizer: http://b/360322720
=> CBL110 - App Dev - Processing Cloud Pub/Sub Data using Cloud Functions: Node.js

self-paced-labs/learning-tensorflow/cnn-challenge-lab/cnn_challenge_lab.ipynb
- Updated the machine type and protobuf==3.20 versions.
- http://b/360968153
=> Classify Images with TensorFlow on Google Cloud: Challenge Lab

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/write_low_level_code.ipynb
Changed `tf.substrac` to `tf.subtract`
=> Fixed typo in write_low_level_code.ipynb

courses/developingapps/v1.2/nodejs/pubsub-languageapi-spanner/end/server/gcp/pubsub.js, courses/developingapps/v1.2/nodejs/pubsub-languageapi-spanner/start/server/gcp/pubsub.js, courses/developingapps/v1.3/nodejs/pubsub-languageapi-spanner/end/server/gcp/pubsub.js, courses/developingapps/v1.3/nodejs/pubsub-languageapi-spanner/start/server/gcp/pubsub.js
=> fix: Fix typo subscrioption -> subscription

self-paced-labs/vertex-ai/vertex-bqml/lab_exercise.ipynb
Based on the hash 10% of the rows are labeled 'test'
=> Fixing the typo

self-paced-labs/cloud-run/canary/Dockerfile, self-paced-labs/cloud-run/canary/README.md, self-paced-labs/cloud-run/canary/app.py, self-paced-labs/cloud-run/canary/branch-cloudbuild.yaml, self-paced-labs/cloud-run/canary/branch-trigger.json-tmpl, self-paced-labs/cloud-run/canary/master-cloudbuild.yaml, self-paced-labs/cloud-run/canary/master-trigger.json-tmpl, self-paced-labs/cloud-run/canary/tag-cloudbuild.yaml, self-paced-labs/cloud-run/canary/tag-trigger.json-tmpl
- Created a `cloud-run/canary` folder.
- Added/Updated the files as per reference of `cloudrun-progression-csr` tag of `software-delivery-workshop` repo.
- Added the service account to the required files.
- Added the options for logging in .yaml files.
- Reference buganizer: http://b/348361326
=> GSP1078 - Cloud Run Canary Deployments

courses/developingapps/v1.3/nodejs/containerengine/start/prepare_environment.sh
- Updated command for npm install
- Added command to install datastore
- Buganizer: http://b/362922349
=> CBL107 - App Dev - Deploying the Application into Kubernetes Engine: Node.js 

courses/developingapps/v1.3/nodejs/pubsub-languageapi-spanner/start/prepare_web_environment.sh
- Updated a command to install latest npm version
- Added a command to install datastore packages
- Reference bug: http://b/367650026
=> CBL108 - Notebook updates

courses/developingapps/v1.3/nodejs/firebase/start/prepare_environment.sh
- Updated a command to install latest npm version
- Added a command to install datastore packages
- Reference bug: http://b/369540156
=> CBL103 - Notebook fixes

quests/vertex-ai/vertex-challenge-lab/vertex-challenge-lab.ipynb
Updated the notebook:
- Added the instructions to install newer version of libaries.
- Added instruction to restart the kernal.
=> GSP354-notebook-updates

courses/developingapps/v1.3/nodejs/cloudstorage/start/prepare_environment.sh
- Updated a command to install latest npm version
- Added a command to install datastore packages
- Reference bug: http://b/375176676
=> CBL114 - Notebook fixes

quests/sparktobq/05_functions_dw.ipynb
=> d6-au-CBL054-sp14

quests/sparktobq/05_functions_dw.ipynb
- Added region flag to avoid location constraint issue
- Reference bug: http://b/377830163
=> CBL054 - Notebook updates

courses/developingapps/v1.3/nodejs/cloudendpoints/start/prepare_environment.sh
- Updated command to include additional arguments for Gen 2 function deplyment
- Added command to grant pubsub.publisher permission to service account
- Updated a command to install latest npm version
- Added a command to install datastore packages
- Reference bug: http://b/379264627
=> CBL105: Notebook Fixes

courses/machine_learning/deepdive2/launching_into_ml/solutions/workbench_explore_data.ipynb
- Updated the formatting of markdown block
- Reference bug: http://b/380825497
=> Formatting updates: workbench_explore_data.ipynb

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/intro_to_vertex_pipelines.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/intro_to_vertex_pipelines.ipynb
- Updated the command to install the `setuptools==59.5.0` packages in main and solution notebook.
- Reference bug: http://b/381510150
=> OCBL273 - Introduction to Vertex Pipelines

self-paced-labs/vertex-ai/train-deploy-tf-model/requirements.txt
One more small change to this.  Need an updated version of openpyxl.
=> Updating openpyxl.

CPB100/lab4c/mlapis.ipynb
- Updated the code in mlapis.ipynb notebook
- Buganizer: http://b/387764278
=> Notebook updates: Invoking Machine Learning APIs

courses/machine_learning/feateng/feateng.ipynb
- Updated the command to install the latest packages.
- Updated the version of tensorflow and pyhon.
- Updated the console link
- Related Buganizer:
=> OCBL040 - Notebook Updates

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/intro_to_vertex_pipelines.ipynb, courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/solutions/intro_to_vertex_pipelines.ipynb
- Updated the notebooks as per changes recommended in the buganizer.
- Reference Buganizer: http://b/384877452
=> OCBL273_notebook-fix

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/model_monitoring_for_custom_model_batch_prediction_job.ipynb
Updated the cell to restart the kernel.
=> Updated the cell to restart the kernel.

courses/developingapps/nodejs/appengine/start/prepare_environment.sh
- Updated the nodejs version __nodejs8__ to __nodejs22__ in `prepare_environment.sh` file
- Buganizer : http://b/393072785
=> App Dev: Deploying the Application into App Engine Flexible Environment v1.1 - Nodejs version update

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/model_monitoring_for_custom_model_batch_prediction_job.ipynb
- Made the ‘Define training dataset’ step as mandatory as there is dependency on the further cells in the notebook
=> Updated the instruction in the notebook

courses/machine_learning/deepdive2/computer_vision_fun/labs/classifying_images_with_transfer_learning.ipynb, courses/machine_learning/deepdive2/computer_vision_fun/solutions/classifying_images_with_transfer_learning.ipynb
- Updated the bucket path in both target and solution notebooks
- Buganizer: http://b/388804811
=> Notebook updates - OCBL337-ClassifyingImagesWithTransferLearning

quests/dataflow/2_Branching_Pipelines/labs/pom.xml, quests/dataflow/2_Branching_Pipelines/solution/pom.xml
- Updated the beam version in pom.xml file
- Buganizer : http://b/410735151
=> Updates : Serverless Data Processing with Dataflow - Branching Pipelines (Java)

courses/business/managingmlprojects/labs/bias_tfdv_facets.ipynb, courses/business/managingmlprojects/solutions/bias_tfdv_facets.ipynb
- Updated the codes as required in the bias_tfdv_facets.ipynb files.
- Updated the output section
- Related Buganizer: http://b/409748551
=> OCBL198 - Notebook Updates

quests/dataflow/3_Batch_Analytics/labs/pom.xml, quests/dataflow/3_Batch_Analytics/solution/pom.xml
- Updated the beam version in pom.xml files
- Buganizer : http://b/409540594
=> DataflowAcademy-030 : Serverless Data Processing with Dataflow - Batch Analytics Pipelines with Dataflow (Java)

quests/dataflow/7_Advanced_Streaming_Analytics/labs/pom.xml, quests/dataflow/7_Advanced_Streaming_Analytics/solution/pom.xml
- Updated the beam version in pom.xml file
- Buganizer: http://b/410978924
=> version update - Serverless Data Processing with Dataflow - Advanced Streaming Analytics Pipeline with Dataflow (Java)

quests/dataflow/8a_Batch_Testing_Pipeline/lab/pom.xml, quests/dataflow/8a_Batch_Testing_Pipeline/solution/pom.xml, quests/dataflow/8b_Stream_Testing_Pipeline/lab/pom.xml, quests/dataflow/8b_Stream_Testing_Pipeline/solution/pom.xml
- Updated the  beam version in  `8a_Batch_Testing_Pipeline > pom.xml` file.
- Updated the  beam version in  `8b_Stream_Testing_Pipeline > pom.xml` file.
- Buganizer : http://b/413302234
=> DataflowAcademy : Serverless Data Processing with Dataflow - Testing with Apache Beam (Java)

quests/dataflow/1_Basic_ETL/labs/pom.xml, quests/dataflow/1_Basic_ETL/solution/pom.xml
- Updated the beam version in pom.xml file
- Buganizer : http://b/412629645
=> DataflowAcademy-010 : Serverless Data Processing with Dataflow - Writing an ETL pipeline using Apache Beam and Dataflow (Java)

quests/dataflow/4_SQL_Batch_Analytics/labs/pom.xml, quests/dataflow/4_SQL_Batch_Analytics/solution/pom.xml, quests/dataflow/4_SQL_Batch_Analytics/solution/src/main/java/com/mypackage/pipeline/BatchUserTrafficSQLPipeline.java
Per b/408390070#comment8 and a conversation with lab owner (Tim Goldstein), this lab updates the necessary files for this lab to run the batch pipeline using `BatchUserTrafficSQLPipeline.java`.
=> Update files for Serverless Data Processing with Dataflow - Using Dataflow SQL for Batch Analytics (Java)

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/model_monitoring_for_custom_model_batch_prediction_job.ipynb
- Updating notebook to replace projectID and location.
=> d6-au-OCBL287-oos

courses/developingapps/v1.3/nodejs/cloudendpoints/start/prepare_environment.sh
- Updated nodejs version in prepare_environment.sh file
-  buganizer: http://b/429965297
=> Updated nodejs version in prepare_environment.sh file

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/1_training_at_scale_vertex.ipynb, courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/1_training_at_scale_vertex.ipynb
- Updating notebook to reflect the below change in cell 3 to avoid error. BUCKET = "PROJECT"
=> d6-au-CBL227-sp17

courses/machine_learning/deepdive2/machine_learning_in_the_enterprise/labs/model_monitoring_for_custom_model_batch_prediction_job.ipynb
- Updated the installation pip command in notebook.
- Reference Buganizer: http://b/431995404
=> OCBL287: Monitoring Vertex AI Models

courses/understanding_spanner/dataflow/csv-to-spanner.py
Changes in PipelineOptions:
- pickle_library='dill' in PipelineOptions
- save_main_session=True
SDK Version:
- Apache Beam Python 3.12 SDK 2.68.0
=> Dataflow pickling error fix
