datalab/create_vm.sh
datalab/start_tunnel.sh

`datalabvm-${USER}` is invalid instance name if `_` is included in `${USER}`.

bug fix: modify to remove underscore from instance name

---

datalab/start_datalab.sh

I came across this repository during my training on [Course CPB100: Google Cloud Platform Big Data & Machine Learning Fundamentals](https://cloud.google.com/training/courses/cpb100). I noticed that a patch was missing in the `start_datalab.sh` script for linux users. This PR addresses the security concern described in googledatalab/datalab/issues/786 . The code was taken directly from the patch in googledatalab/datalab/issues/850 .

On linux bind to localhost only so docker does not expose the port

---

datalab/start_datalab.sh

This PR includes the following changes to the `start_datalab.sh` script used to run Cloud Datalab locally:
-  Allow users to easily set the Datalab notebook/config by setting `CONTENT`
- `PROJECT_ID` has moved to the top of the file to make it easier to set the project id
- `docker run -t` has changed to `docker run -it` to match the [Datalab Quickstart document](https://cloud.google.com/datalab/docs/quickstarts/quickstart-local)
- The `&` in the docker run command has been removed to make it easier for users to stop the running Datalab Docker container (and for consistency with the quick start doc)

Update the start_datalab.sh to add ability to set the notebook directory

---

courses/machine_learning/datasets/create_datasets.ipynb

IPython notebook interprets code within $ .. $ as [MathJax expressions](http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Typesetting%20Equations.html#Inline-Typesetting-(Mixing-Markdown-and-TeX)). Escape with \$ to display the dollar sign properly.
Before: 
After:

Escape $ sign in IPython notebook

---

courses/machine_learning/tensorflow/d_experiment.ipynb

This patch fixes the following error resulting from the following code:
`from datalab.ml import TensorBoard`
Error message:
```
ImportErrorTraceback (most recent call last)
<ipython-input-8-c683d951966c> in <module>()
----> 1 from datalab.ml import TensorBoard
2 TensorBoard().start('./taxi_trained')
3 TensorBoard().list()
ImportError: No module named ml
```

Fix Tensorboard import error

---

courses/data_analysis/lab2/python/grep.py
courses/data_analysis/lab2/python/grepc.py

Existing code checks for import in any text which returns false positives. This now checks for lines that start with import.

Fix check for import lines to use a regex

---

CPB100/lab4a/demandforecast.ipynb

The MIN() function is extraneous here, as each day of year should only ever fall on the same day of week (and if it doesn't, that suggests a problem in our data).

Removing extraneous aggregation operation

---

CPB100/lab4a/demandforecast.ipynb

The current code for doing this conversion is less intuitive and does in two lines what could be easily done in one. This method also better adheres to what seems like convention around adding columns to a Pandas Dataframe.

Updating Conversion from Continuous to Categorical

---

courses/machine_learning/tensorflow/b_tflearn.ipynb

I'm adding print_rmse for the Deep NN regression on the validation set as this (I think!) needs to be done before claiming that "We are not beating our benchmark with either model" (as done in the subsequent text cell)

Print RMSE for NN on the validation set

---

courses/machine_learning/tensorflow/a_tfstart.ipynb

Just as the overloaded "+" operator is explained, "*" should be too, particularly in light of the fact that it's not a matrix multiplication operation.

Adding helpful comment

---

blogs/babyweight/train_deploy.ipynb

Received an invalid bucket name error in Datalab. Added $ to copy command so it would reference the environment variable set in previous cell.

Fixed bucket name command typos

---

blogs/babyweight/babyweight.ipynb

Hi. This is just to fix a typo in the headline.

Fix: typo in the headline

---

courses/machine_learning/feateng/feateng.ipynb

The code for the old 'BigQuery to Tensorflow' python file has moved to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cloud/python/ops/bigquery_reader_ops.py (the old link was broken), but now an official documentation page for this package exists: https://www.tensorflow.org/api_docs/python/tf/contrib/cloud/BigQueryReader
The official documentation is probably a better starting point for a beginner than the module code.

Replaced broken link with official Tensorflow documentation

---

courses/streaming/publish/README.txt

Pub/Sub python client 0.29.0 introduces breaking changes for streaming code. Specifying an older version provides a workaround until scripts can be appropriately rewritten.

specify pub/sub version to avoid backwards-compatibility issues

---

blogs/babyweight/babyweight.ipynb

Hi, "gcloud ml-engine models create" need to be uncommented by default for the initial execution (as supposed by the solution document.)

Create a new model for prediction service by default.

---

courses/data_analysis/lab2/python/JavaProjectsThatNeedHelp.py

If you look at the [compositeScore call](https://github.com/dulacp/training-data-analyst/blob/master/courses/data_analysis/lab2/python/JavaProjectsThatNeedHelp.py#L172), then the first argument is element from the popular list, and the second is the dict of `needs_help` packages.
That's why I switch the two parameters names :)
Cheers

Switch popular and help variable names, because it doesn't match inputs

---

courses/machine_learning/feateng/taxifare/trainer/task.py

Output_dir was getting clobbered during hyperparameter tuning. Ryan fixed it, I tested. Now works for both feateng and hyperparam notebooks.

fixed output dir arg to work with TF 1.4+

---

courses/machine_learning/feateng/taxifare/trainer/model.py

Column order of the tuple didn't match order of the list created above. This should improve RMSEs in v12 considerably...

Fix column order in model.py

---

courses/machine_learning/datasets/create_datasets.ipynb

Students are unfamiliar with the concept of linear regression at the time when they are working with this notebook. This part of the plot causes confusion (e.g. is the line part of the data points? what does the line mean?) and side discussions from students who already know about linear regression (e.g. what's the error with the linear regression in Seaborn?). This part of the plot should be also be removed because it is not pertinent to the content of the notebook.

Remove the linear regression line on the plot

---

courses/machine_learning/deepdive/05_artandscience/simplernn/trainer/model.py

Already did this for d_customestimator.ipynb, need to do this here in model.py too

Fixed export_outputs for SignatureDef MetaGraph

---

courses/machine_learning/deepdive/03_tensorflow/debug_demo.ipynb

with a special keyword argumnet: `ui_type="readline"`

tfdbg LocalCLIDebugWrapperSession works in CoLab

---

courses/machine_learning/deepdive/09_sequence/poetry.ipynb

using parameter `problem` instead of `problemes` fixes error:
p.s. see discussion https://gitter.im/tensor2tensor/Lobby?at=5b0273bdf04ce53632f379ce
```
File "/root/.local/lib/python2.7/site-packages/tensor2tensor/utils/registry.py", line 251, in parse_problem_name
if problem_name.endswith("_rev"):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

fixed parameter name `problems` -> `problem`

---

courses/machine_learning/deepdive/06_structured/labs/5_train.ipynb

Noticed a tiny typo in the bootcamp today. Great set of materials! Thanks y'all!

Fix Typo (edtis -> edits) in Lab 5

---

courses/data_analysis/lab2/python/grep.py
courses/data_analysis/lab2/python/grepc.py

This pull request is to revise the codes as per discussed in #225. `grep.py` and `grepc.py` in _training-data-analyst/courses/data_analysis/lab2/python/_ have been modified accordingly.

Use str.startswith method instead of re.match

---

courses/machine_learning/deepdive/08_image/labs/flowersmodel/model.py

When we adapted the MNIST model to handle RGB, we forgot to change our reshape.

Fixing shape errors cause by RGB images

---

courses/machine_learning/deepdive/08_image/flowersmodel/model.py

When we adapted the MNIST model for use with RGB images, we forgot to change our reshape to be HEIGHT * WIDTH * NUM_CHANNELS

Fixing shape errors by RGB images

---

courses/machine_learning/deepdive/09_sequence/txtclsmodel/trainer/model.py
courses/machine_learning/deepdive/09_sequence/txtclsmodel/trainer/model_native.py

simplifies Keras -> Estimator integration. 
Passing tensor directly works instead of having to sync dictionary key with keras input layer name.

removed dictionary wrapping of tensor in input_fn

---

courses/machine_learning/deepdive/09_sequence/text_classification_native.ipynb

This pull request fixes a bug in the notebook which references variables that haven't been set in the notebook (techcrunch+nytimes+github).

added sample prediction instances to resolve bug with unreferenced variables

---

blogs/babyweight/babyweight.ipynb

I think the number of training steps for MLE job is mistakingly changed to 20000 in the past commit: fbac8bf0
This reverts it to the original value 100000.

Fix: revert MLE training steps to 100000

---

courses/machine_learning/deepdive/06_structured/4_preproc.ipynb
courses/machine_learning/deepdive/06_structured/4_preproc_tft.ipynb
courses/machine_learning/deepdive/06_structured/labs/4_preproc.ipynb
courses/machine_learning/deepdive/08_image/flowers_fromscratch.ipynb
courses/machine_learning/deepdive/08_image/flowers_fromscratch_tpu.ipynb

region _'If not set, defaults to us-central1'_  https://cloud.google.com/dataflow/docs/guides/specifying-exec-params  which might differ from the region of the output bucket specified in the notebook before if it was changed from default 'us-central1' and data locality _'minimize network latency and network transport costs'_ https://cloud.google.com/dataflow/docs/concepts/regional-endpoints#why_specify_a_regional_endpoint

adds region to pipeline options

---

courses/machine_learning/deepdive/04_features/a_features.ipynb

There's a typo in the text that describes the actions performed in the Training and Evaluation section

Typo in the instructions

---

courses/machine_learning/feateng/tftransform.ipynb

It seems strange that the Euclidean distance was left in its raw form. It probably ought to be normalized just like the examples of latdiff and londiff.
This pull request scales it between 0 and 1 based on the training data.

Update tftransform.ipynb normalize euclidean

---

courses/machine_learning/deepdive/06_structured/pipelines/2_deploy_kubeflow_pipelines.sh

Below command failed with "error: resource(s) were provided, but no name, label selector, or --all flag specified" error so updating the job option:
(before) # kubectl wait --for=condition=complete --timeout=5m $jobname
(after) # kubectl wait --for=condition=complete --timeout=5m job/$jobname

Update kubectl wait option

---

courses/developingapps/nodejs/appengine/start/prepare_environment.sh

prepare_environment.sh was throwing an error that --runtime is required as we experienced in training class with @turbomanage

Fixing requires --runtime error

---

courses/bdml_fundamentals/demos/earthquakevm/transform.py

Fix for duplicate URL provided on script, due to function not using the value passed as parameters (#484)

replaced URL with value provided as parameter

---

courses/machine_learning/deepdive/10_recommend/content_based_preproc.ipynb
courses/machine_learning/deepdive/10_recommend/labs/content_based_preproc.ipynb

The BigQuery link in the notebook points to the welcome page of the (legacy) BigQuery Web UI. As the project always is a fresh, new (Qwiklabs) project, the project & data list is empty.
Finding the data set is a chore and you really need to scan it to solve the TODO (get custom dimension index). This link directly opens the data set.

Replace general BigQuery with link to task-specific data set

---

courses/machine_learning/images/mnist_linear.ipynb

Removing a reference in the instructions to estimator as we no longer teach the estimator api.
Thanks for the review, team!

Removing reference to estimator

---

courses/machine_learning/deepdive2/text_classification/solutions/custom_tf_hub_word_embedding.ipynb

With tensorflow_hub==0.7.0 we can directly use KerasLayer without the wrapper. 
Updated the lab with this info.

Update KerasLayer with new version of tensorflow_hub

---

courses/machine_learning/deepdive2/time_series_prediction/solutions/3_modeling_bqml.ipynb

When using magics like '%%biquery', this has to be on the first line, else it fails with "syntax error at create or update model". So moving the comment lines that were above it, to under it.

Moving the %%bigquery magic to the first line of code blocks.

---

courses/machine_learning/deepdive/03_tensorflow/labs/a_tfstart.ipynb

Replaced reference to 'tf.where_loop' with 'tf.while_loop' in hint comment.

Fixed typo 'tf.where_loop' to 'tf.while_loop'

---

quests/genomics/vcf-to-bigquery/run.sh

STAGING_BUCKET already has a gs:// prefix. Removed the redundant gs:// prefix from --logging as it was causing a failure

STAGING_BUCKET already has a gs:// prefix, which caused an error

---

README.md

fix Open in Cloud Shell link (was 404ing)

---

quests/serverlessml/07_caip/labs/export_data.ipynb
quests/serverlessml/07_caip/labs/train_caip.ipynb
quests/serverlessml/07_caip/solution/export_data.ipynb
quests/serverlessml/07_caip/solution/train_caip.ipynb

- Added the chown and TF 2.x install command in export_data.ipynb.
- Updated the execution_count in both notebooks.

TF Migration 1.x >> TF 2.x: CBL076 - ML Workshop: Train ML model on Cloud AI Platform

---

courses/ahybrid/v1.0/AHYBRID050/scripts/create_gke.sh

- THIS IS A HOTFIX; LAB USING CURRENT FILES IS BROKEN
- Updated cluster to regular channel
- Updated ASM install to 1.6.8

1.73/1.04 RELEASE: AHYBRID050 UPDATED TO ASM 1.6.8

---

courses/ahybrid/v1.0/AHYBRID045/scripts/create_gke.sh
courses/ahybrid/v1.0/AHYBRID045/scripts/install.sh

- added continutation character to gcloud command
- removed kpt which isn't needed
This is for the 1.7.4/1.0.5 release, to be pushed today 10/9

AHYBRID045-BUG-FIX-RELEASE-CHANNEL

---

quests/bq-optimize/demos/code/information_schema.sql

This PR updates the information_schema.sql file that is used for demos in the DE course 1: Modernizing Data Lakes and Data Warehouses with GCP.  These update address the permission error from the last query (previously the first query) that runs on the BigQuery Public Data project.  The query and comments have been modified to indicate that the query should be run in learners' projects (e.g. qwiklabs-gcp-XX-XXXXXXXXXX), not on the BigQuery Public Data project.

Update Information_Schema demo for DE

---

quests/dei/census/income_xgboost.ipynb
quests/dei/xgboost_caip_e2e.ipynb

Receiving errors or calls for user input without due to recent updates. Also adds more clarity to command as there's been confusion regarding endpoints used in commands.

add global region to ai-platform commands in whatif notebooks

---

courses/machine_learning/deepdive2/structured/labs/5a_train_keras_ai_platform_babyweight.ipynb

Different path from solution notebook and this cause error during trainng.
Solution:
https://github.com/GoogleCloudPlatform/training-data-analyst/blob/6f9f731d0b2202c06259c8eac389c7dd5c0d8930/courses/machine_learning/deepdive2/structured/solutions/5a_train_keras_ai_platform_babyweight.ipynb#L231

fixed importing path mismatch

---

courses/ahybrid/v1.0/common/scripts/acm.sh
courses/ahybrid/v1.0/common/scripts/c2.sh
courses/ahybrid/v1.0/common/scripts/create_gke.sh
courses/ahybrid/v1.0/common/scripts/create_remote.sh

We discovered a few problems with the anthos setup files only after pushing to production. This branch resolves those:
* Inserted sleep statements to resolve problem with activated service not being recognized as enabled
* Changed gke cluster reservation to use workload identity
* Changed remote cluster creation script to successfully copy/use the config file

Anthos April21 Post-publication fixes

---

self-paced-labs/ai-platform-qwikstart/ai_platform_qwik_start.ipynb

The aim of this PR is to fix a minor typo in the [ ai_platform_qwik_start.ipynb](https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/self-paced-labs/ai-platform-qwikstart/ai_platform_qwik_start.ipynb) notebook.

Fix minor typo in `ai_platform_qwik_start.ipynb` notebook

---

courses/machine_learning/feateng/feateng.ipynb

This is a super simple typo fix in a comment. Specify was written without an i initially.

MAINT: correctly spell specify

---

quests/dei/census/income_xgboost.ipynb
quests/dei/what-if-tool-challenge.ipynb

fix typo
rename func `limited_custom_predict` to `bad_custom_predict` match with WitConfigBuilder in https://www.qwiklabs.com/focuses/12011?parent=catalog

fix typo, rename wrong function

---

blogs/babyweight/application/app.yaml
blogs/babyweight/application/main.py
blogs/babyweight/application/requirements.txt
blogs/babyweight_keras/babyweight.ipynb

Hi, I applied a few fixes to the babyweight_keras notebook and the associated app.
babyweight_keras notebook
- Add  `--region=global` option to `gcloud ai-platform versions create` command.
- Replace Estimator in the section title with Keras.
associated app
- Update config and codes for AppEngine 2nd generation (Python3)

Fixes babyweight_keras notebook and associated app for latest versions of AppEngine and AI Platform

---

courses/machine_learning/deepdive2/introduction_to_tensorflow/labs/3_keras_sequential_api.ipynb
courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/3_keras_sequential_api.ipynb

- Removed the command to set ai platform/region to 'global' as it is a deprecated endpoint.
- Reference buganizer: http://b/192671052

Notebook_update: 3_keras_sequential_api.ipynb

---

blogs/microservices-demo-1/src/adservice/build.gradle

This is meant to address the log4j vulnerability omg/45447.
- Please validate the fix and working
- If this requires additional updates, let's consider deprecating.

Upgrade log4j = 2.16.0

---

quests/vertex-ai/vertex-challenge-lab/vertex-challenge-lab.ipynb
self-paced-labs/vertex-ai/vertex-challenge-lab/vertex-challenge-lab-solution.ipynb

- Updated the training time in the target and solution notebook accordingly as pipeline takes around 38 minutes to succeed.
- Reference buganizer: http://b/207523058

GSP354 - vertex-challenge-lab.ipynb 

---

courses/ak8s/v1.1/Cloud_SQL/sql-proxy.yaml

In this pull request, the sql-proxy.yaml was updated in the following way:
1. The version of  - name: cloudsql-proxy
image: gcr.io/cloudsql-docker/gce-proxy:1.11 was updated to the :latest flag, as deployment was continually failing. The :latest flag did not allow a deployment when applied to the wordpress image.

Ss ms cbl155 cloudsql b263851689 oos

---

quests/vertex-ai/vertex-challenge-lab/requirements.txt
quests/vertex-ai/vertex-challenge-lab/vertex-challenge-lab.ipynb

Users of Qwiklab GSP354 which uses this repo (specifically the notebook vertex-challenge-lab.ipynb) reported bugs when running the pipeline. Lab was taken offline for maintenance. We identified the Python libraries and Docker images needed to be updated, since the last commit is over 2 years old. This PR should solve it. Can you please expedite the approval so we can bring the lab back online?

Updated libraries and docker image versions

---

self-paced-labs/vertex-ai/vertex-ai-qwikstart/requirements.txt

The latest version of google-cloud-aiplatform[tensorboard] is 1.22.0, needed to fix b/270080160

updated version to 1.22.0

---

quests/vertex-ai/vertex-challenge-lab/vertex-challenge-lab.ipynb

On March 31st, there was a change in the Vertex AI Prediction Docker image which caused this pipeline to fail. Somehow the image does not contain Python anymore, so you cannot install libraries. We are going to need to pin the prediction image to guarantee the pipeline works.

using correct Docker images

---

quests/vertex-ai/vertex-challenge-lab/vertex-challenge-lab.ipynb

As requested by the Vertex Serving team, we should be using the latest image for prediciton. They are backwards compatible.

Update the prediction image to use the latest build

---

courses/machine_learning/deepdive2/mlops_vertexai_manage_features/labs/feature_store_streaming_ingestion_sdk.ipynb

Update to Feature Store Notebook to implment correct pip module installation. 
Lab has been trested against this and the notebook is currently only used with OCBL431.

d6-jm-certex-ai-forecasting-notebook-update

---

courses/developingapps/v1.2/python/appengine/end/frontend/requirements.txt
courses/developingapps/v1.2/python/appengine/end/requirements.txt
courses/developingapps/v1.2/python/appengine/start/frontend/requirements.txt
courses/developingapps/v1.2/python/appengine/start/requirements.txt
courses/developingapps/v1.2/python/kubernetesengine/bonus/answer_backend/requirements.txt
courses/developingapps/v1.2/python/kubernetesengine/bonus/backend/requirements.txt
courses/developingapps/v1.2/python/kubernetesengine/bonus/frontend/requirements.txt
courses/developingapps/v1.2/python/kubernetesengine/bonus/requirements.txt
courses/developingapps/v1.2/python/kubernetesengine/end/backend/requirements.txt
courses/developingapps/v1.2/python/kubernetesengine/end/frontend/requirements.txt
courses/developingapps/v1.2/python/kubernetesengine/end/requirements.txt
courses/developingapps/v1.2/python/kubernetesengine/start/backend/requirements.txt
courses/developingapps/v1.2/python/kubernetesengine/start/frontend/requirements.txt
courses/developingapps/v1.2/python/kubernetesengine/start/requirements.txt
courses/developingapps/v1.3/python/appengine/end/frontend/requirements.txt
courses/developingapps/v1.3/python/appengine/end/requirements.txt
courses/developingapps/v1.3/python/appengine/start/frontend/requirements.txt
courses/developingapps/v1.3/python/appengine/start/requirements.txt
courses/developingapps/v1.3/python/kubernetesengine/bonus/answer_backend/requirements.txt
courses/developingapps/v1.3/python/kubernetesengine/bonus/backend/requirements.txt
courses/developingapps/v1.3/python/kubernetesengine/bonus/frontend/requirements.txt
courses/developingapps/v1.3/python/kubernetesengine/bonus/requirements.txt
courses/developingapps/v1.3/python/kubernetesengine/end/backend/requirements.txt
courses/developingapps/v1.3/python/kubernetesengine/end/frontend/requirements.txt
courses/developingapps/v1.3/python/kubernetesengine/end/requirements.txt
courses/developingapps/v1.3/python/kubernetesengine/start/backend/requirements.txt
courses/developingapps/v1.3/python/kubernetesengine/start/frontend/requirements.txt
courses/developingapps/v1.3/python/kubernetesengine/start/requirements.txt

I want to fix the issue on GKE.
urllib3 v2.0 only supports OpenSSL 1.1.1+
See: https://github.com/urllib3/urllib3/issues/2168
However, `gcr.io/google_appengine/python` is currently providing "OpenSSL 1.0.2g  1 Mar 2016". Therefore, the code in `courses/developingapps/v1.3/python/kubernetesengine` will not work properly.
You will need to add:
```
urllib3<2.0
```
Additionally, a similar issue could occur with `courses/developingapps/v1.3/python/appengine`. But as of 2023-10-28, `python_version: 3` refers to Python 3.6. And when `pip3 install -r /app/requirements.txt` is executed in Python 3.6, `urllib3<2.0` seems to be automatically added due to dependency issues. Therefore, it appears there is currently no issue with App Engine Flexible (although I propose a change). …

Fix Python requirements for `courses/developingapps/v1.3/python`

---

self-paced-labs/vertex-ai/vertex-ai-qwikstart/requirements.txt

Deps are out of date, breaking workflow for: https://www.cloudskillsboost.google/games/3306/labs/20551
More info:
If you follow the instructions and use the newest 2.x per these instructions "In the New instance menu, choose the latest version of TensorFlow Enterprise 2.x in Environment" there are broken dependencies.  When you download the data and convert it to csv pandas cant run.
internal ref: b/323433962

Update requirements.txt - fixing broken deps in codelab

---

self-paced-labs/ai-platform-qwikstart/ai_platform_qwik_start.ipynb

- Updated the TF version to `2.11` in `ai_platform_qwik_start.ipynb` notebook.
- Buganzier : http://b/325014437

GSP076 : Vertex AI Workbench Notebook: Qwik Start (Notebook Update)

---

courses/machine_learning/deepdive2/text_classification/labs/reusable_embeddings.ipynb
courses/machine_learning/deepdive2/text_classification/solutions/reusable_embeddings.ipynb

Removed the deployment step to ensure the lab can run in the restrictive Qwiklab enviornemnt.
Changes include:
- Removed one learning objective about model deployment.
- Removed the step of model deployment.
Two notebooks have been impacted:
- reusable_embeddings.ipynb under lab folder
- reusable_embeddings.ipynb under solution folder

textEmbedding-removed deployment

---

self-paced-labs/vertex-ai/vertex-ai-qwikstart/requirements.txt

upgraded pyarrow from existing 6.0.0 to 7.0.0 for the initial gsp lab 917  at https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/self-paced-labs/vertex-ai/vertex-ai-qwikstart/lab_exercise.ipynb
A similar pr  https://github.com/GoogleCloudPlatform/training-data-analyst/pull/2612  and my comment be seen here -> https://github.com/GoogleCloudPlatform/training-data-analyst/pull/2612#issuecomment-2120490633

upgrade pyarrow

---

self-paced-labs/vertex-ai/vertex-ai-qwikstart/lab_exercise.ipynb

This PR remove 2nd learning objective from Vertex AI Qwik Start notebook titled lab_exercise.ipynb because it is not actually achieved (it was mistakenly kept in the notebook after it was created from the longer notebook titled lab_exercise_long.ipynb).

Remove 2nd learning objective from Vertex AI Qwik Start notebook
